[CmdletBinding()]
param([Parameter(Mandatory)][string]$ProjectRoot,[string]$OutputPath)

$ErrorActionPreference='Stop'
$project=(Resolve-Path -LiteralPath $ProjectRoot).Path
if(-not $OutputPath){$OutputPath=Join-Path $project '.studio/REPO_MAP.json'}
$skip='(?i)(^|[\\/])(?:\.git|node_modules|vendor|dist|build|out|coverage|\.next|\.cache|tmp)([\\/]|$)'
function Rel([string]$Path){$Path.Substring($project.Length).TrimStart('\','/').Replace('\','/')}
function Files([string[]]$Names){@(Get-ChildItem -LiteralPath $project -Recurse -File -ErrorAction SilentlyContinue|Where-Object{$_.FullName -notmatch $skip -and $Names -contains $_.Name}|Sort-Object FullName)}
$packages=@(Files @('package.json'));$py=@(Files @('pyproject.toml','requirements.txt','Pipfile'));$configs=@(Files @('next.config.js','next.config.mjs','next.config.ts','vite.config.ts','vite.config.js','tsconfig.json','tailwind.config.js','tailwind.config.ts','playwright.config.ts','vitest.config.ts','jest.config.js','prisma.schema','docker-compose.yml'))
$languages=[Collections.Generic.List[string]]::new();$frameworks=[Collections.Generic.List[string]]::new();$commands=[ordered]@{install='';lint='';typecheck='';test='';build='';dev=''};$manager='';$manifests=@($packages+$py|ForEach-Object{Rel $_.FullName}|Sort-Object -Unique)
if(Test-Path (Join-Path $project 'pnpm-lock.yaml')){$manager='pnpm'}elseif(Test-Path (Join-Path $project 'yarn.lock')){$manager='yarn'}elseif(Test-Path (Join-Path $project 'package-lock.json')){$manager='npm'}elseif($packages){$manager='npm'}
foreach($package in $packages){$json=Get-Content -Raw -LiteralPath $package.FullName|ConvertFrom-Json;$languages.Add('javascript');if(Test-Path (Join-Path $package.DirectoryName 'tsconfig.json')){$languages.Add('typescript')};$deps=@();if($json.PSObject.Properties['dependencies']){$deps+=$json.dependencies.psobject.Properties.Name};if($json.PSObject.Properties['devDependencies']){$deps+=$json.devDependencies.psobject.Properties.Name};if($deps -contains 'next'){$frameworks.Add('nextjs')};if($deps -contains 'react'){$frameworks.Add('react')};if($deps -contains 'express'){$frameworks.Add('express')};if($json.PSObject.Properties['scripts']){foreach($key in @($commands.Keys)){if(-not $commands[$key] -and $json.scripts.PSObject.Properties[$key]){$commands[$key]="$manager run $key"}}}}
if($py){$languages.Add('python')};$roots=[ordered]@{sourceRoots=@();frontendRoots=@();serverRoots=@();databaseRoots=@();integrationRoots=@();testRoots=@()};foreach($name in @('src','app','pages','apps','packages','server','api','backend','lib','tests','test','__tests__','prisma','db','database','integrations')){$p=Join-Path $project $name;if(Test-Path -LiteralPath $p -PathType Container){$r=Rel $p;if($name -in @('src','app','pages','apps','packages')){$roots.sourceRoots+=$r};if($name -in @('src','app','pages')){$roots.frontendRoots+=$r};if($name -in @('server','api','backend')){$roots.serverRoots+=$r};if($name -in @('prisma','db','database')){$roots.databaseRoots+=$r};if($name -eq 'integrations'){$roots.integrationRoots+=$r};if($name -in @('tests','test','__tests__')){$roots.testRoots+=$r}}}
$commit='';try{$commit=(git -C $project rev-parse HEAD 2>$null).Trim()}catch{};$router=if($frameworks -contains 'nextjs'){if(Test-Path (Join-Path $project 'app')){'app'}elseif(Test-Path (Join-Path $project 'pages')){'pages'}else{'unknown'}}else{''}
$map=[ordered]@{generatedAt=[DateTime]::UtcNow.ToString('o');sourceCommit=$commit;packageManager=$manager;languages=@($languages|Sort-Object -Unique);frameworks=@($frameworks|Sort-Object -Unique);routerMode=$router;sourceRoots=@($roots.sourceRoots|Sort-Object -Unique);frontendRoots=@($roots.frontendRoots|Sort-Object -Unique);serverRoots=@($roots.serverRoots|Sort-Object -Unique);databaseRoots=@($roots.databaseRoots|Sort-Object -Unique);integrationRoots=@($roots.integrationRoots|Sort-Object -Unique);testRoots=@($roots.testRoots|Sort-Object -Unique);styleSystem=if(Test-Path (Join-Path $project 'tailwind.config.ts')){'tailwind'}elseif(Test-Path (Join-Path $project 'tailwind.config.js')){'tailwind'}else{''};configFiles=@($configs|ForEach-Object{Rel $_.FullName}|Sort-Object);manifestFiles=$manifests;commands=$commands;ownershipHints=[ordered]@{};detectedRisks=@();unknowns=@();provenance=[ordered]@{commands='package.json scripts; absent commands are empty';stack='package manifests and configuration only'}}
if(-not $map.sourceRoots.Count){$map.unknowns+=@('sourceRoots')};if(-not $map.commands.test){$map.unknowns+=@('test command')};New-Item -ItemType Directory -Force -Path (Split-Path $OutputPath) | Out-Null;$map|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $OutputPath -Encoding utf8;Write-Host "Repository map generated: $OutputPath"
