[CmdletBinding()]
param([Parameter(Mandatory)][string]$ProjectRoot,[Parameter(Mandatory)][string]$Role,[Parameter(Mandatory)][string]$State,[ValidateSet('lean','standard','thorough')][string]$Mode='standard',[Parameter(Mandatory)][string]$Task,[string[]]$AffectedPath=@())

$ErrorActionPreference='Stop';$project=(Resolve-Path -LiteralPath $ProjectRoot).Path;$studio=Join-Path $project '.studio';$root=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path
if(-not(Test-Path $studio)){throw 'Missing .studio project state.'};$map=Join-Path $studio 'REPO_MAP.json';if(-not(Test-Path $map)){& (Join-Path $PSScriptRoot 'build_repo_map.ps1') -ProjectRoot $project|Out-Null};& (Join-Path $PSScriptRoot 'resolve_rules.ps1') -ProjectRoot $project -Mode $Mode|Out-Null
$budgets=@{lean=@(8000,12000);standard=@(16000,24000);thorough=@(30000,45000)}[$Mode];function Rel([string]$p){$p.Substring($project.Length).TrimStart('\','/').Replace('\','/')};function Read([string]$p){if(Test-Path $p){Get-Content -Raw -LiteralPath $p}else{''}};function Exists([string]$p){Test-Path -LiteralPath (Join-Path $studio $p)}
$base=@('PROJECT_SNAPSHOT.md','PROJECT_STATE.md','ACTIVE_AND_DEFERRED_SCOPE.md','ACCEPTANCE_CRITERIA.md');$byRole=@{ 'product-studio'=@('PROJECT_BRIEF.md','CONFIRMED_FACTS.md','ASSUMPTIONS.md','APPROVED_CONCEPT.md');'frontend-builder'=@('APPROVED_CONCEPT.md','COPY.md','DESIGN_SYSTEM.md','IMPLEMENTATION_PLAN.md');'backend-builder'=@('BACKEND_SPEC.md','API_CONTRACT.md','SECURITY_MODEL.md');'database-architect'=@('DATABASE_DECISION.md','DATA_MODEL.md','MIGRATION_PLAN.md','DATA_RETENTION.md','SECURITY_MODEL.md');'integration-builder'=@('INTEGRATION_SPEC.md','ENVIRONMENT_CONTRACT.md','API_CONTRACT.md','SECURITY_MODEL.md');'test-engineer'=@('IMPLEMENTATION_PLAN.md','TECH_DECISION.md');'code-reviewer'=@('IMPLEMENTATION_PLAN.md','TECH_DECISION.md');'browser-qa'=@('APPROVED_CONCEPT.md','DESIGN_SYSTEM.md','IMPLEMENTATION_PLAN.md');};$required=@($base+$byRole[$Role]|Where-Object{Exists $_}|Sort-Object -Unique);$optional=@();$mapData=Get-Content -Raw $map|ConvertFrom-Json;$stack=@($mapData.frameworks)+@($mapData.languages)
$index=Get-Content -Raw (Join-Path $root 'knowledge/context/RULE_ROUTE_INDEX.json')|ConvertFrom-Json;$rules=@($index.rules|Where-Object{$_.roles -contains $Role -and ($_.stages -contains $State -or $_.stages -contains 'implementation')}|Where-Object{(!$_.stacks.Count) -or @($_.stacks|Where-Object{$stack -contains $_}).Count}|Sort-Object @{e='priority';Descending=$true},id);$hard=@($rules|Where-Object{$_.strength -eq 'hard'});$details=@($rules|ForEach-Object{$_.source}|Sort-Object -Unique)
$cards=@();if($Role -in @('frontend-builder','browser-qa')){$cards=@(Get-ChildItem -LiteralPath (Join-Path $studio 'references/cards') -Filter '*.md' -File -ErrorAction SilentlyContinue|Sort-Object Name|Select-Object -First $(if($Mode -eq 'lean'){3}elseif($Mode -eq 'standard'){5}else{999})|ForEach-Object{Rel $_.FullName})}
$reports=@(Get-ChildItem -LiteralPath (Join-Path $studio 'reports') -File -ErrorAction SilentlyContinue|Where-Object{$_.Name -notmatch '(?i)(superseded|rejected|historical)'}|Sort-Object LastWriteTimeUtc -Descending|Select-Object -First $(if($Mode -eq 'lean'){1}elseif($Mode -eq 'standard'){2}else{6})|ForEach-Object{Rel $_.FullName})
$paths=@($AffectedPath|ForEach-Object{$_ -replace '\\','/'}|Sort-Object -Unique);if($Role -eq 'code-reviewer' -and -not $paths.Count){try{$paths=@(git -C $project diff --name-only 2>$null|Where-Object{$_}|ForEach-Object{$_ -replace '\\','/'}|Sort-Object -Unique)}catch{}};$reasons=[ordered]@{};foreach($record in $required){$reasons[$record]=if($base -contains $record){'active project routing baseline'}else{"required by $Role role bundle"}};$snapshotTokens=0;$recordTokens=0;$cardTokens=0;$evidenceTokens=0;foreach($p in $required){$full=Join-Path $studio $p;if(Test-Path $full){$size=[Text.Encoding]::UTF8.GetByteCount((Read $full))/4;if($p -eq 'PROJECT_SNAPSHOT.md'){$snapshotTokens+=$size}else{$recordTokens+=$size}}};foreach($p in $cards){$cardTokens+=[Text.Encoding]::UTF8.GetByteCount((Read (Join-Path $project $p)))/4};foreach($p in $reports){$evidenceTokens+=[Text.Encoding]::UTF8.GetByteCount((Read (Join-Path $project $p)))/4};$ruleTokens=(($rules|ConvertTo-Json -Compress).Length/4);$embedded=$snapshotTokens+$recordTokens+$cardTokens+$evidenceTokens+$ruleTokens;$status=if($embedded -gt $budgets[1]){'exceeded'}elseif($embedded -gt $budgets[0]){'warning'}else{'within-target'}
$manifest=[ordered]@{schemaVersion=1;generatedAt=[DateTime]::UtcNow.ToString('o');projectRoot=$project;projectState=$State;workflowMode=$Mode;role=$Role;task=$Task;productType='';stack=@($stack|Sort-Object -Unique);activeScope=@($required|Where-Object{$_ -eq 'ACTIVE_AND_DEFERRED_SCOPE.md'});requiredRecords=$required;recordReasons=$reasons;optionalRecords=$optional;selectedRuleIds=@($rules|ForEach-Object id);ruleDetailSources=$details;selectedReferenceCards=$cards;repositoryPaths=$paths;latestEvidence=$reports;excludedContext=@([ordered]@{path='superseded/rejected/historical reports';reason='excluded by default'});budget=[ordered]@{mode=$Mode;approximateTokenLimit=$budgets[0];approximateSelectedTokens=[Math]::Ceiling($embedded);status=$status;breakdown=[ordered]@{projectSnapshot=[Math]::Ceiling($snapshotTokens);selectedProjectRecords=[Math]::Ceiling($recordTokens);selectedRuleSummaries=[Math]::Ceiling($ruleTokens);detailedRuleSources=0;referenceCards=[Math]::Ceiling($cardTokens);previousEvidence=[Math]::Ceiling($evidenceTokens);repositoryDocumentation=0;sourcePathsListedNotEmbedded=0}};unresolved=@();warnings=@()}
if($status -eq 'exceeded'){$manifest.warnings+=@('Budget exceeded; stage additional optional context rather than truncate hard rules or required records. Largest contributors: project records, cards, and previous evidence.')} ;$runtime=Join-Path $studio 'runtime/context';New-Item -ItemType Directory -Force -Path $runtime|Out-Null;$json=Join-Path $runtime ($Role+'.json');$md=Join-Path $runtime ($Role+'.md');$manifest|ConvertTo-Json -Depth 10|Set-Content -LiteralPath $json -Encoding utf8;@("# Context manifest: $Role",'',"- Task: $Task","- Mode: $Mode","- Approximate embedded tokens: $([Math]::Ceiling($embedded)) ($status)","- Required records: $($required -join ', ')","- Rule IDs: $($manifest.selectedRuleIds -join ', ')","- Repository paths: $($paths -join ', ')","- Referenced source files are not embedded. Runtime behavior and host file reading remain unverified.")|Set-Content -LiteralPath $md -Encoding utf8;Write-Host "Context manifest generated: $json"
