[CmdletBinding()]
param([Parameter(Mandatory)][string]$ProjectRoot,[Parameter(Mandatory)][string]$Role,[string]$State,[ValidateSet('lean','standard','thorough')][string]$Mode,[string]$Task,[string[]]$AffectedPath=@(),[switch]$Diagnostic,[switch]$Force)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'ContextCompilerHelpers.ps1')
. (Join-Path $PSScriptRoot '../security/Test-AuthorizedPath.ps1')
. (Join-Path $PSScriptRoot '../security/Test-ProjectRelativePath.ps1')
$project=(Resolve-Path -LiteralPath $ProjectRoot).Path;$studio=Join-Path $project '.studio';$root=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path
$stateRecord=Get-ContextRecord $project 'PROJECT_STATE.md' -Required;$stateData=$stateRecord.data
foreach($field in 'currentState','productType','workflowMode','surfaces'){Require-ContextProperty $stateData $field}
$canonicalState=[string]$stateData.currentState;$canonicalMode=[string]$stateData.workflowMode;$surfaces=@($stateData.surfaces);$productType=[string]$stateData.productType
if($State -and $State -ne $canonicalState){Throw-ContextError 'CONTEXT_STATE_CONFLICT'};if($Mode -and $Mode -ne $canonicalMode){Throw-ContextError 'CONTEXT_MODE_CONFLICT'};$effectiveMode=$canonicalMode
$registry=Get-ContextJson (Join-Path $root 'knowledge/context/CONTEXT_ROUTE_REGISTRY.json');$route=@($registry.roles|Where-Object role -eq $Role|Select-Object -First 1);if(-not $route){Throw-ContextError 'CONTEXT_ASSIGNMENT_MISSING'}
$planPath=Join-Path $studio 'reports/specialist-plan.json';$plan=Get-ContextJson $planPath 'CONTEXT_PLAN_MISSING' 'CONTEXT_PLAN_STALE';$planNode=@($plan.nodes|Where-Object id -eq $Role|Select-Object -First 1);if(-not $planNode -or $planNode.status -ne 'ready'){Throw-ContextError 'CONTEXT_PLAN_STALE'}
$assignmentPath=Join-Path $studio ('runtime/assignments/'+$Role+'.json');$assignment=Get-ContextJson $assignmentPath 'CONTEXT_ASSIGNMENT_MISSING' 'CONTEXT_ASSIGNMENT_STALE';if($assignment.status -ne 'ready'){Throw-ContextError 'CONTEXT_ASSIGNMENT_BLOCKED'};if($assignment.role -ne $Role){Throw-ContextError 'CONTEXT_ASSIGNMENT_ROLE_MISMATCH'}
if($Task -and @($assignment.taskIds) -notcontains $Task){Throw-ContextError 'CONTEXT_TASK_CONFLICT'};foreach($path in @($AffectedPath)+@($assignment.allowedPaths)){if($path -and -not(Test-ProjectRelativePath $project $path -AllowGlob).valid){Throw-ContextError 'CONTEXT_PATH_CONFLICT'}}
$scopeRecord=Get-ContextRecord $project 'ACTIVE_AND_DEFERRED_SCOPE.md' -Required;$active=@(Require-ContextProperty $scopeRecord.data 'active');$taskIds=@($assignment.taskIds);$criteriaIds=@($assignment.criteriaIds);$allowed=@($assignment.allowedPaths)
$selectedScope=@();foreach($entry in $active){$entryId=Require-ContextProperty $entry 'id';$entrySurfaces=Get-ContextArray $entry 'surfaces';$entryTasks=@(Get-ContextArray $entry 'taskIds')+@(Get-ContextArray $entry 'relatedTasks');$entryCriteria=@(Get-ContextArray $entry 'acceptanceCriteria')+@(Get-ContextArray $entry 'criteriaIds');$entryPaths=@(Get-ContextArray $entry 'affectedPaths')+@(Get-ContextArray $entry 'relevantPaths');$relevant=((@($entryTasks|Where-Object{$_ -in $taskIds}).Count -gt 0) -or (@($entryCriteria|Where-Object{$_ -in $criteriaIds}).Count -gt 0) -or (@($entrySurfaces|Where-Object{$_ -in @(Get-ContextArray $assignment 'surfaces')}).Count -gt 0));if(($allowed.Count -gt 0) -and ($entryPaths.Count -gt 0)){$relevant=($relevant -and (@($entryPaths|Where-Object{$_ -in $allowed}).Count -gt 0))};if($relevant){$selectedScope+=[ordered]@{id=$entryId;status='active';surfaces=$entrySurfaces;relatedTasks=$entryTasks;relatedCriteria=$entryCriteria;relevantPaths=$entryPaths;selectedBecause='Assignment task, criteria, surface, and allowed-path overlap.'}}}
if(-not $selectedScope.Count){Throw-ContextError 'CONTEXT_TASK_CONFLICT'}
$recordNames=@($route.mandatoryRecords);foreach($p in @($route.conditionalRecords.PSObject.Properties)){if($surfaces -contains $p.Name){$recordNames+=@($p.Value)}};$records=@();$excluded=@();foreach($name in @($recordNames|Sort-Object -Unique)){$r=Get-ContextRecord $project $name -Required;$records+=Get-ContextItem $r.path 'record' 'Mandatory or applicable conditional registry record.' $name}
$mapPath=Join-Path $studio 'REPO_MAP.json';$repo=@();$mapItem=$null;if([bool]$route.includeRepositoryMap){if(-not(Test-Path $mapPath)){& (Join-Path $PSScriptRoot 'build_repo_map.ps1') -ProjectRoot $project|Out-Null};$mapItem=Get-ContextItem $mapPath 'repository-map' 'Registry requires repository map.' 'REPO_MAP';$repo=@($assignment.allowedPaths|Sort-Object)}
$mapStacks=@();if($mapItem){$map=Get-ContextJson $mapPath 'CONTEXT_RECORD_INVALID' 'CONTEXT_RECORD_INVALID';$mapStacks=@(Get-ContextArray $map 'frameworks')+@(Get-ContextArray $map 'languages')+@(Get-ContextArray $map 'stacks')}
$ruleIndex=Get-ContextJson (Join-Path $root 'knowledge/context/RULE_ROUTE_INDEX.json')
$rules=@($ruleIndex.rules|Where-Object {
  $rule=$_;$ruleSurfaces=@(Get-ContextArray $rule 'surfaces');$ruleProducts=@(Get-ContextArray $rule 'productTypes');$ruleStacks=@(Get-ContextArray $rule 'stacks');$groups=@(Get-ContextArray $rule 'ruleGroup');$routeGroups=@(Get-ContextArray $route 'ruleGroups');$roleOk=(($rule.roles -contains '*') -or ($rule.roles -contains $Role));$stateOk=(($rule.stages -contains '*') -or ($rule.stages -contains $canonicalState));$surfaceOk=(($ruleSurfaces.Count -eq 0) -or (@($ruleSurfaces|Where-Object{$_ -in $surfaces}).Count -gt 0));$productOk=(($ruleProducts.Count -eq 0) -or ($ruleProducts -contains $productType));$stackOk=(($ruleStacks.Count -eq 0) -or (@($ruleStacks|Where-Object{$_ -in $mapStacks}).Count -gt 0));$groupOk=(($groups.Count -eq 0) -or (@($groups|Where-Object{$_ -in $routeGroups}).Count -gt 0));($roleOk -and $stateOk -and $surfaceOk -and $productOk -and $stackOk -and $groupOk)
}|Sort-Object @{Expression='priority';Descending=$true},@{Expression='id';Descending=$false})
$ruleItems=@($rules|ForEach-Object{[ordered]@{id=$_.id;category='rule';selectionReason='Registry group and canonical route match.';estimatedTokens=[math]::Ceiling($_.summary.Length/4);contentFingerprint=Get-ContextHash $_}})
$deltas=@();$deltaDir=Join-Path $studio 'reports/deltas';if(Test-Path $deltaDir){foreach($f in Get-ChildItem $deltaDir -Filter '*.json' -File|Sort-Object Name){try{$d=Get-ContextJson $f.FullName;if((@($assignment.predecessors)+@($route.relevantDeltaRoles)) -contains $d.role){$deltas+=Get-ContextItem $f.FullName 'delta' 'Assignment predecessor or registry delta role.' $d.role}else{$excluded+=[ordered]@{path=$f.FullName;category='delta';reason='Role is outside relevantDeltaRoles.'}}}catch{$excluded+=[ordered]@{path=$f.FullName;category='delta';reason='Invalid delta.'}}}}
$cards=@();$linksPath=Join-Path $studio 'references/PROJECT_REFERENCE_LINKS.json';$cardsRoot=Join-Path $studio 'references/cards';if((Test-Path $linksPath) -and (Test-Path $cardsRoot)){foreach($link in @(Get-ContextJson $linksPath 'CONTEXT_REQUIRED_RECORD_MISSING' 'CONTEXT_RECORD_INVALID')|Sort-Object referenceId){$card=Join-Path $cardsRoot ($link.referenceId+'.json');if(-not(Test-Path $card)){$excluded+=[ordered]@{path=$card;category='reference-card';reason='Linked card missing.'};continue};$data=Get-ContextJson $card;$cardRoles=@(Get-ContextArray $data 'roles')+@(Get-ContextArray $data 'tags');$roleOverlap=@($cardRoles|Where-Object{$_ -in @(Get-ContextArray $route 'referenceRoles')}).Count;if(($link.approved -ne $true) -or ($data.status -ne 'active') -or ($roleOverlap -eq 0)){$excluded+=[ordered]@{path=$card;category='reference-card';reason='Unapproved, inactive, or role-unrelated.'};continue};$cards+=([ordered]@{id=$link.referenceId;path=$card;category='reference-card';selectedRole=$link.role;selectedBecause='Approved project link and relevant registry reference role.';contentFingerprint=Get-ContextHash (Get-Content -Raw $card);estimatedTokens=[math]::Ceiling((Get-Content -Raw $card).Length/4);untrustedContent=$true;noCopyBoundary=$data.noCopy})}}
$limit=@{lean=2;standard=5;thorough=999}[$effectiveMode];$cards=@($cards|Select-Object -First $limit);$contributors=@($records)+@($ruleItems)+@($deltas)+@($cards)+@($mapItem|Where-Object{$_});$estimated=(@($contributors|ForEach-Object estimatedTokens|Measure-Object -Sum).Sum);$target=@{lean=8000;standard=16000;thorough=30000}[$effectiveMode];$warning=@{lean=12000;standard=24000;thorough=45000}[$effectiveMode]
$fingerprintInput=[ordered]@{schema=3;projectIdentity=$project;role=$Role;mode=$effectiveMode;projectState=$canonicalState;productType=$productType;activeScope=$selectedScope;assignment=$assignment;plan=$plan;records=@($records|ForEach-Object contentFingerprint);rules=@($ruleItems|ForEach-Object contentFingerprint);registry=Get-ContextHash (Get-Content -Raw (Join-Path $root 'knowledge/context/CONTEXT_ROUTE_REGISTRY.json'));ruleIndex=Get-ContextHash (Get-Content -Raw (Join-Path $root 'knowledge/context/RULE_ROUTE_INDEX.json'));overlay=Get-ContextHash (Get-Content -Raw (Join-Path $root 'knowledge/context/RULE_ROUTE_OVERLAY.json'));deltas=@($deltas|ForEach-Object contentFingerprint);cards=@($cards|ForEach-Object contentFingerprint);repositoryMap=if($mapItem){$mapItem.contentFingerprint}else{''};approval=Get-ContextHash $records;technicalDecisions=@($records|Where-Object id -eq 'TECH_DECISION.md'|ForEach-Object contentFingerprint);securityRecords=@($records|Where-Object{$_.id -match 'SECURITY|THREAT'}|ForEach-Object contentFingerprint)};$fingerprint=Get-ContextHash $fingerprintInput
$runtime=Join-Path $studio 'runtime/context';New-Item -ItemType Directory -Force $runtime|Out-Null;$output=Join-Path $runtime ($Role+'.json');$cache='miss';if((Test-Path $output) -and -not $Force){try{$old=Get-ContextJson $output;$missing=@($old.contributors|Where-Object{$_.PSObject.Properties['path'] -and $_.path -and -not(Test-Path $_.path)});if(($old.schemaVersion -eq 3) -and ($old.projectIdentity -eq $project) -and ($old.role -eq $Role) -and ($old.workflowMode -eq $effectiveMode) -and ($old.fingerprint -eq $fingerprint) -and ($missing.Count -eq 0)){$cache='hit'}else{$cache='stale'}}catch{$cache='stale'}}
$manifest=[ordered]@{schemaVersion=3;status='ready';projectIdentity=$project;role=$Role;workflowMode=$effectiveMode;projectState=$canonicalState;productType=$productType;surfaces=@($assignment.surfaces);assignmentPath=$assignmentPath;taskIds=$taskIds;criteriaIds=$criteriaIds;activeScope=$selectedScope;selectedRecords=$records;selectedRules=$ruleItems;selectedRuleIds=@($ruleItems|ForEach-Object id);selectedReferenceCards=$cards;selectedDeltas=$deltas;repositoryPaths=$repo;excludedItems=$excluded;estimatedTokens=$estimated;targetTokens=$target;warningTokens=$warning;budgetStatus=if($estimated -gt $warning){'exceeded'}elseif($estimated -gt $target){'warning'}else{'within-target'};contributors=$contributors;stages=if($estimated -gt $warning){@('core','contracts','references','history')}else{@('core')};fingerprint=$fingerprint;fingerprintInputs=$fingerprintInput;cacheStatus=$cache;invalidatedBy=@();blockingReasons=@()};$indexPath=Join-Path $studio 'CONTEXT_INDEX.json';Write-AtomicTextFile $project $indexPath (([ordered]@{schemaVersion=2;authoritativeRecords=@($records|ForEach-Object path);specialistPlan=$planPath;assignments=@($assignmentPath);generatedManifests=@($output);blockers=@()})|ConvertTo-Json -Depth 12);Write-AtomicTextFile $project $output ($manifest|ConvertTo-Json -Depth 40);Write-Host "Context manifest generated: $output (ready)"
