. (Join-Path $PSScriptRoot 'Read-StudioRecord.ps1')

function Test-StudioValue { param($Value) if($null -eq $Value){return $false}; $text=([string]$Value).Trim(); return $text -and $text -notmatch '(?i)^(?:tbd|todo|unknown|placeholder|template|\[.*\])$' }
function Add-StudioError { param($List,[string]$Path,[string]$Type,[string]$Field,[string]$Value,[string]$Reason) $List.Add([pscustomobject][ordered]@{path=$Path;recordType=$Type;missingField=$Field;invalidValue=$Value;status='';blockingReason=$Reason}) }

function Test-StudioRecord {
 [CmdletBinding()]
 param([Parameter(Mandatory)][string]$Path,[string]$ExpectedRecordType,[switch]$Required,[string[]]$RequiredSurfaces=@())
 $record=Read-StudioRecord -Path $Path;$errors=[Collections.Generic.List[object]]::new();$type=$ExpectedRecordType
 if(-not $record.exists){if($Required){Add-StudioError $errors $Path $type 'record' 'missing' 'Required record is missing.'};return [pscustomobject]@{valid=$false;record=$record;errors=@($errors);status='missing'}}
 if($null -eq $record.metadata){Add-StudioError $errors $Path $type 'metadata' $(if($record.legacy){'legacy-unstructured'}else{'invalid-json'}) (($record.errors|Select-Object -First 1).blockingReason);return [pscustomobject]@{valid=$false;record=$record;errors=@($errors);status='invalid'}}
 $m=$record.metadata;$type=[string]$m.recordType
 foreach($field in @('schemaVersion','recordType','status','owner','updatedAt','applicability','sources','data')){if($null -eq $m.$field){Add-StudioError $errors $Path $type $field 'missing' 'Required envelope field is missing.'}}
 if($m.schemaVersion -ne 1){Add-StudioError $errors $Path $type 'schemaVersion' ([string]$m.schemaVersion) 'Only schemaVersion 1 is supported.'}
 if($ExpectedRecordType -and $m.recordType -ne $ExpectedRecordType){Add-StudioError $errors $Path $type 'recordType' ([string]$m.recordType) "Expected record type $ExpectedRecordType."}
 if(@('draft','blocked','superseded') -contains $m.status -and $Required){Add-StudioError $errors $Path $type 'status' ([string]$m.status) 'A required record is not ready.'}
 if($m.status -eq 'not-applicable' -and $Required){Add-StudioError $errors $Path $type 'status' 'not-applicable' 'Routing requires this record.'}
 if(-not (Test-StudioValue $m.owner)){Add-StudioError $errors $Path $type 'owner' ([string]$m.owner) 'Owner is incomplete.'}
 if(-not $m.applicability -or $null -eq $m.applicability.productTypes -or $null -eq $m.applicability.surfaces){Add-StudioError $errors $Path $type 'applicability' 'missing' 'Applicability must contain productTypes and surfaces.'}
 if($m.status -eq 'not-applicable' -and -not (Test-StudioValue $m.data.reason)){Add-StudioError $errors $Path $type 'data.reason' 'missing' 'not-applicable requires a non-empty reason.'}
 if(-not $record.body -or $record.body -match '(?is)^#?\s*(?:record|template|todo|tbd|project state)\s*$'){Add-StudioError $errors $Path $type 'body' 'empty-or-template' 'Record body has no meaningful human-readable context.'}
 switch($ExpectedRecordType){
  'project-state' { foreach($f in @('currentState','productType','workflowMode','surfaces','runnable','risks','nextRequiredTransition')){if($null -eq $m.data.$f){Add-StudioError $errors $Path $type "data.$f" 'missing' 'Required project state field is missing.'}};if($m.data.workflowMode -notin @('lean','standard','thorough')){Add-StudioError $errors $Path $type 'data.workflowMode' ([string]$m.data.workflowMode) 'Invalid workflow mode.'};if(-not (Test-StudioValue $m.data.productType)){Add-StudioError $errors $Path $type 'data.productType' ([string]$m.data.productType) 'Product type must be known.'};if(@($m.data.surfaces).Count -eq 0){Add-StudioError $errors $Path $type 'data.surfaces' 'empty' 'Active surfaces are required.'} }
  'active-scope' { if(@($m.data.active).Count -eq 0){Add-StudioError $errors $Path $type 'data.active' 'empty' 'Active scope must contain an item.'};foreach($i in @($m.data.active)){if(-not(Test-StudioValue $i.id) -or -not(Test-StudioValue $i.title) -or @($i.surfaces).Count -eq 0 -or @($i.acceptanceCriteria).Count -eq 0){Add-StudioError $errors $Path $type 'data.active' 'incomplete' 'Each active scope item needs id, title, surfaces, and acceptance criteria.'}} }
  'approved-concept' { if($m.status -ne 'approved' -or $m.data.approval.status -ne 'approved'){Add-StudioError $errors $Path $type 'approval.status' ([string]$m.data.approval.status) 'Approval record must be approved.'};foreach($f in @('approvedAt','approvedBy','source')){if(-not(Test-StudioValue $m.data.approval.$f)){Add-StudioError $errors $Path $type "data.approval.$f" 'missing' 'Explicit traceable approval evidence is required.'}} }
  'design-system' { if($RequiredSurfaces -contains 'frontend-visible'){foreach($f in @('designThesis','signatureElement','gridStrategy','compositionMap','responsivePlan','tasteResolution')){if($null -eq $m.data.$f){Add-StudioError $errors $Path $type "data.$f" 'missing' 'Visible frontend requires complete design-system data.'}};if(-not(Test-StudioValue $m.data.designThesis)){Add-StudioError $errors $Path $type 'data.designThesis' 'empty' 'Visible frontend requires a design thesis.'};if(-not(Test-StudioValue $m.data.gridStrategy.columnModel) -or @($m.data.gridStrategy.containers).Count -eq 0 -or -not(Test-StudioValue $m.data.gridStrategy.gutters) -or @($m.data.gridStrategy.breakpoints).Count -eq 0){Add-StudioError $errors $Path $type 'data.gridStrategy' 'incomplete' 'Visible frontend requires grid and responsive strategy.'}} }
  'implementation-plan' { if(@($m.data.tasks).Count -eq 0){Add-StudioError $errors $Path $type 'data.tasks' 'empty' 'Implementation plan needs tasks.'};foreach($t in @($m.data.tasks)){if(-not(Test-StudioValue $t.id) -or -not(Test-StudioValue $t.owner) -or @($t.acceptanceCriteria).Count -eq 0 -or (@($t.affectedPaths).Count -eq 0 -and -not(Test-StudioValue $t.pendingPathReason))){Add-StudioError $errors $Path $type 'data.tasks' 'incomplete' 'Task requires owner, acceptance mapping, and paths or pending-path reason.'}} }
  'acceptance-criteria' { if(@($m.data.criteria).Count -eq 0){Add-StudioError $errors $Path $type 'data.criteria' 'empty' 'Acceptance criteria require an active criterion.'};foreach($c in @($m.data.criteria)){if(-not(Test-StudioValue $c.id) -or -not(Test-StudioValue $c.behavior) -or -not(Test-StudioValue $c.surface) -or @($c.evidenceTypes).Count -eq 0){Add-StudioError $errors $Path $type 'data.criteria' 'incomplete' 'Criterion requires id, behavior, surface, and evidence types.'}} }
  'copy' { if(@($m.data.sections).Count -eq 0 -or -not(Test-StudioValue $m.data.contentLedgerPath)){Add-StudioError $errors $Path $type 'data' 'incomplete' 'Copy record needs sections and content-ledger path.'} }
 }
 [pscustomobject]@{valid=($errors.Count -eq 0);record=$record;errors=@($errors);status=if($errors.Count){'invalid'}else{'valid'}}
}
