Set-StrictMode -Version Latest
function Get-PathComparison { if($IsWindows){[StringComparison]::OrdinalIgnoreCase}else{[StringComparison]::Ordinal} }
function Test-PathInsideRoot { param([string]$Root,[string]$Candidate) $r=[IO.Path]::GetFullPath($Root).TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar);$c=[IO.Path]::GetFullPath($Candidate);$c.Equals($r,(Get-PathComparison)) -or $c.StartsWith($r+[IO.Path]::DirectorySeparatorChar,(Get-PathComparison)) }
function Test-AuthorizedPath {
 [CmdletBinding()]param([Parameter(Mandatory)][string]$Root,[Parameter(Mandatory)][string]$Path,[switch]$AllowGlob,[switch]$RequireExisting)
 $out=[ordered]@{valid=$false;resolved='';errorCode=''}
 if([string]::IsNullOrWhiteSpace($Path) -or $Path -match '[\x00-\x1f]'){$out.errorCode='PATH_CONTROL_CHARACTER';return [pscustomobject]$out}
 if($Path -match '^(?:\\\\[?.]|\\\\[.])'){$out.errorCode='PATH_DEVICE';return [pscustomobject]$out}
 if([IO.Path]::IsPathRooted($Path) -or $Path -match '^[A-Za-z]:'){$out.errorCode='PATH_ABSOLUTE';return [pscustomobject]$out}
 if($Path -match '(^|[\\/])\.\.([\\/]|$)'){$out.errorCode='PATH_TRAVERSAL';return [pscustomobject]$out}
 if($Path -match '(^|[\\/])\.git([\\/]|$)' -or $Path -match '(?i)(^|[\\/])\.web-studio-agent([\\/]|$)'){$out.errorCode='PATH_FORBIDDEN';return [pscustomobject]$out}
 if($Path -match ':'){$out.errorCode='PATH_ADS';return [pscustomobject]$out};if($Path -match '[*?]' -and -not $AllowGlob){$out.errorCode='PATH_GLOB_FORBIDDEN';return [pscustomobject]$out};if($Path -match '^(?:\*\*|\*|[\\/]?\*\*)'){$out.errorCode='PATH_GLOB_BROAD';return [pscustomobject]$out}
 if($IsWindows){foreach($part in ($Path -split '[\\/]')){if($part -and $part -ne '.' -and ($part -match '[. ]$' -or $part -match '^(?i:CON|NUL|PRN|AUX|COM[0-9]+|LPT[0-9]+)(?:\..*)?$')){$out.errorCode='PATH_WINDOWS_RESERVED';return [pscustomobject]$out}}}
 try{$physicalRoot=(Resolve-Path -LiteralPath $Root -ErrorAction Stop).Path}catch{$out.errorCode='PATH_ROOT_RESOLUTION_FAILED';return [pscustomobject]$out};$candidate=[IO.Path]::GetFullPath((Join-Path $physicalRoot ($Path -replace '[*?]','_glob_')));if(-not(Test-PathInsideRoot $physicalRoot $candidate)){$out.errorCode='PATH_OUTSIDE_ROOT';return [pscustomobject]$out}
 $static=$Path -replace '[*?].*$','';$walk=$physicalRoot;foreach($part in ($static -split '[\\/]'|Where-Object{$_ -and $_ -ne '.'})){ $next=Join-Path $walk $part;if(Test-Path -LiteralPath $next){$entry=Get-Item -LiteralPath $next -Force;if($entry.Attributes -band [IO.FileAttributes]::ReparsePoint){$out.errorCode='PATH_PHYSICAL_ESCAPE';return [pscustomobject]$out};try{$physical=(Resolve-Path -LiteralPath $next -ErrorAction Stop).Path}catch{$out.errorCode='PATH_PHYSICAL_RESOLUTION_FAILED';return [pscustomobject]$out};if(-not(Test-PathInsideRoot $physicalRoot $physical)){$out.errorCode='PATH_PHYSICAL_ESCAPE';return [pscustomobject]$out};$walk=$physical}else{break}}
 if($RequireExisting -and -not(Test-Path -LiteralPath $candidate)){$out.errorCode='PATH_NOT_FOUND';return [pscustomobject]$out};$out.valid=$true;$out.resolved=$candidate;[pscustomobject]$out
}
function Assert-AuthorizedPath { param([string]$Root,[string]$Path,[switch]$AllowGlob,[switch]$RequireExisting) $result=Test-AuthorizedPath @PSBoundParameters;if(-not $result.valid){throw $result.errorCode};$result.resolved }
function Write-AtomicTextFile { param([string]$Root,[string]$Destination,[string]$Content) $relative=[IO.Path]::GetRelativePath([IO.Path]::GetFullPath($Root),[IO.Path]::GetFullPath($Destination));$target=Assert-AuthorizedPath $Root $relative;$parent=Split-Path $target -Parent;if(-not(Test-Path $parent)){New-Item -ItemType Directory -Force -Path $parent|Out-Null};$parentRelative=[IO.Path]::GetRelativePath([IO.Path]::GetFullPath($Root),$parent);Assert-AuthorizedPath $Root $parentRelative|Out-Null;$tmp=Join-Path $parent ('.tmp-'+[guid]::NewGuid().ToString('N'));[IO.File]::WriteAllText($tmp,$Content,[Text.UTF8Encoding]::new($false));$stream=[IO.File]::Open($tmp,[IO.FileMode]::Open,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None);$stream.Flush($true);$stream.Dispose();Assert-AuthorizedPath $Root $relative|Out-Null;Move-Item -LiteralPath $tmp -Destination $target -Force }
