Set-StrictMode -Version Latest
. (Join-Path $PSScriptRoot 'security/Test-AuthorizedPath.ps1')
. (Join-Path $PSScriptRoot 'security/Test-PotentialSecret.ps1')

function Get-ReferencePolicy { Get-Content -Raw (Join-Path $PSScriptRoot '../schemas/reference-ingest-policy.json') | ConvertFrom-Json }
function Resolve-ReferenceLibraryRoot {
  param([string]$AgentHome = $env:WEB_STUDIO_AGENT_HOME)
  if (-not $AgentHome) { $AgentHome = if ($IsWindows) { Join-Path $env:USERPROFILE '.web-studio-agent' } else { Join-Path $HOME '.web-studio-agent' } }
  $homePath = [IO.Path]::GetFullPath($AgentHome)
  if ($homePath -match '(?i)[\\/]plugins[\\/]cache(?:[\\/]|$)') { throw 'LIBRARY_HOME_PLUGIN_CACHE' }
  if (-not (Test-Path $homePath)) { New-Item -ItemType Directory -Force -Path $homePath | Out-Null }
  if ((Get-Item $homePath).Attributes -band [IO.FileAttributes]::ReparsePoint) { throw 'LIBRARY_HOME_REPARSE_POINT' }
  Join-Path $homePath 'reference-library'
}
function Initialize-ReferenceLibrary {
  param([string]$AgentHome = $env:WEB_STUDIO_AGENT_HOME)
  $library=Resolve-ReferenceLibraryRoot $AgentHome
  if(-not(Test-Path $library)){New-Item -ItemType Directory -Force -Path $library|Out-Null}
  if((Get-Item $library).Attributes -band [IO.FileAttributes]::ReparsePoint){throw 'LIBRARY_ROOT_REPARSE_POINT'}
  foreach($name in 'references','indexes','schemas','migrations','reports','tmp'){New-Item -ItemType Directory -Force -Path (Join-Path $library $name)|Out-Null}
  $library
}
function ConvertTo-NormalizedReferenceUrl {
  param([Parameter(Mandatory)][string]$Url)
  try{$uri=[Uri]$Url}catch{throw 'URL_INVALID'}
  if(-not $uri.IsAbsoluteUri -or $uri.Scheme -notin @('https','http')){throw 'URL_SCHEME_FORBIDDEN'}
  if($uri.UserInfo){throw 'URL_CREDENTIALS_FORBIDDEN'}
  $sensitive='^(token|access_token|api_key|key|secret|signature|auth|authorization|password|session|code|credential|jwt)$';$tracking='^(utm_.*|gclid|fbclid|yclid|mc_.*|ref|referrer|referral)$'
  $query=@();foreach($part in $uri.Query.TrimStart('?').Split('&',[StringSplitOptions]::RemoveEmptyEntries)){$bits=$part.Split('=',2);$n=[Uri]::UnescapeDataString($bits[0]);if($n -match "(?i)$sensitive" -or $n -match "(?i)$tracking"){continue};$v=if($bits.Count -gt 1){[Uri]::UnescapeDataString($bits[1])}else{''};$query+=([Uri]::EscapeDataString($n)+'='+[Uri]::EscapeDataString($v))}
  $b=[UriBuilder]$uri;$b.Scheme=$uri.Scheme.ToLowerInvariant();$b.Host=$uri.Host.ToLowerInvariant();$b.Fragment='';if(($b.Scheme -eq 'https' -and $b.Port -eq 443) -or ($b.Scheme -eq 'http' -and $b.Port -eq 80)){$b.Port=-1};$b.Path=if($b.Path.TrimEnd('/')){$b.Path.TrimEnd('/')}else{'/'};$b.Query=($query|Sort-Object)-join '&';$b.Uri.AbsoluteUri.TrimEnd('/')
}
function Escape-ReferenceMarkdown { param([string]$Text) (($Text -replace '[\x00-\x1f]',' ' -replace '\|','\\|' -replace '<!--','&lt;!--' -replace '```','` ` `') -replace '^[\s]*[-*+]','\\$0') }
function Get-ReferenceItems { param([string]$Library) @(Get-ChildItem -LiteralPath (Join-Path $Library 'references') -Directory -Force|Where-Object{-not($_.Attributes -band [IO.FileAttributes]::ReparsePoint)}|ForEach-Object{$m=Join-Path $_.FullName 'metadata.json';if(Test-Path $m){Get-Content -Raw $m|ConvertFrom-Json}}) }
function Enter-ReferenceLibraryLock { param([string]$Library,[int]$TimeoutSeconds=15) $path=Join-Path $Library '.reference-library.lock';$end=[DateTime]::UtcNow.AddSeconds($TimeoutSeconds);do{try{return [IO.File]::Open($path,[IO.FileMode]::CreateNew,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None)}catch [IO.IOException]{Start-Sleep -Milliseconds 100}}while([DateTime]::UtcNow -lt $end);throw 'LIBRARY_LOCK_TIMEOUT' }
function Exit-ReferenceLibraryLock { param($Lock,[string]$Library) if($Lock){$Lock.Dispose();Remove-Item -LiteralPath (Join-Path $Library '.reference-library.lock') -Force -ErrorAction SilentlyContinue} }
function Test-ReferenceSource {
  param([string]$FilePath,[string]$Library)
  $policy=Get-ReferencePolicy;if(-not(Test-Path -LiteralPath $FilePath -PathType Leaf)){throw 'SOURCE_NOT_REGULAR_FILE'};$item=Get-Item -LiteralPath $FilePath -Force;if($item.Attributes -band [IO.FileAttributes]::ReparsePoint){throw 'SOURCE_REPARSE_POINT'};$full=[IO.Path]::GetFullPath($FilePath);if($full -match '(?i)([\\/]\.git[\\/]|plugins[\\/]cache|reference-library|[\\/]\.cache[\\/])'){throw 'SOURCE_LOCATION_FORBIDDEN'}
  $ext=[IO.Path]::GetExtension($item.Name).ToLowerInvariant();if($item.Name -in @($policy.forbiddenExactNames) -or $ext -in @($policy.forbiddenExtensions) -or $ext -notin @($policy.allowedExtensions) -or $item.Name -match '(?i)\.(env|key|pem|sql|zip)\.'){throw 'SOURCE_EXTENSION_FORBIDDEN'};if($item.Length -gt [int64]$policy.maximumFileSizeBytes){throw 'SOURCE_TOO_LARGE'}
  $bytes=[IO.File]::ReadAllBytes($full);$magic=@{'.png'='89504e47';'.jpg'='ffd8ff';'.jpeg'='ffd8ff';'.gif'='47494638';'.webp'='52494646';'.pdf'='25504446'};if($magic.ContainsKey($ext)){if($bytes.Length -lt 8 -or -not (([BitConverter]::ToString($bytes[0..7])-replace '-','').ToLowerInvariant().StartsWith($magic[$ext]))){throw 'SOURCE_MAGIC_MISMATCH'}}
  $signals=@();$status='not-applicable';if($ext -in @($policy.textLikeExtensions)){$text=[Text.Encoding]::UTF8.GetString($bytes);$scan=Test-PotentialSecret $text $item.Name;if($scan.detected){throw ('SOURCE_SECRET_DETECTED:'+$scan.category)};$status='clear';foreach($p in 'ignore (?:previous|system) instructions','(?:send|upload).*(?:secret|repository)','run (?:this |the )?command','change (?:the )?(?:scope|rules)'){if($text -match "(?i)$p"){$signals+=$p}}}
  [pscustomobject]@{path=$full;name=$item.Name;hash=(Get-FileHash -LiteralPath $full -Algorithm SHA256).Hash.ToLowerInvariant();secretScanStatus=$status;promptSignals=@($signals|Select-Object -Unique);limitations=@('Binary images and PDFs are not proven secret-free.')}
}
function Write-ReferenceIndexes { param([string]$Library) $items=@(Get-ReferenceItems $Library|Sort-Object id);Write-AtomicTextFile $Library (Join-Path $Library 'indexes/REFERENCE_INDEX.json') ($items|ConvertTo-Json -Depth 12);$md="# reference index`n`n| ID | Title | Source type |`n| --- | --- | --- |`n";foreach($i in $items){$md+='| '+(Escape-ReferenceMarkdown $i.id)+' | '+(Escape-ReferenceMarkdown $i.title)+' | '+(Escape-ReferenceMarkdown $i.sourceType)+" |`n"};Write-AtomicTextFile $Library (Join-Path $Library 'indexes/REFERENCE_INDEX.md') $md }
function Add-ReferenceProjectLink { param([string]$ProjectRoot,[string]$ReferenceId,[string]$Role='unassigned',[string]$Reason='Linked from permanent library; approval required before use.',[string]$AgentHome=$env:WEB_STUDIO_AGENT_HOME) $library=Initialize-ReferenceLibrary $AgentHome;if(@(Get-ReferenceItems $library|Where-Object id -eq $ReferenceId).Count -ne 1){throw 'PROJECT_LINK_UNKNOWN_REFERENCE'};$project=(Resolve-Path $ProjectRoot).Path;$dir=Join-Path $project '.studio/references';New-Item -ItemType Directory -Force $dir|Out-Null;$file=Join-Path $dir 'PROJECT_REFERENCE_LINKS.json';$links=@(if(Test-Path $file){Get-Content -Raw $file|ConvertFrom-Json});if(-not @($links|Where-Object{$_.referenceId -eq $ReferenceId -and $_.role -eq $Role}).Count){$links+=,[ordered]@{referenceId=$ReferenceId;role=$Role;reason=$Reason}};Write-AtomicTextFile $project $file ($links|ConvertTo-Json -Depth 8);$md="# project reference index`n`n"+(($links|ForEach-Object{'- `'+(Escape-ReferenceMarkdown $_.referenceId)+'` — role: '+(Escape-ReferenceMarkdown $_.role)})-join "`n");Write-AtomicTextFile $project (Join-Path $dir 'PROJECT_REFERENCE_INDEX.md') $md }
function Add-ReferenceLibraryItem {
  [CmdletBinding()]param([Parameter(Mandatory)][string]$AgentHome,[string]$FilePath,[string]$Url,[string]$Title='Untitled reference',[string]$ProjectRoot,[string[]]$Industries=@(),[string[]]$Platforms=@('web'),[string[]]$StyleFamilies=@(),[string[]]$VisualModifiers=@(),[string]$PrimaryRole='visual',[string[]]$SecondaryRoles=@(),[string[]]$ProjectTypes=@(),[string[]]$StrongSections=@(),[string[]]$SupportedSurfaces=@())
  if(($FilePath -and $Url) -or (-not $FilePath -and -not $Url)){throw 'SOURCE_EXACTLY_ONE_REQUIRED'};$library=Initialize-ReferenceLibrary $AgentHome;$lock=Enter-ReferenceLibraryLock $library;$temp=$null
  try{$info=$null;$normalized=$null;if($FilePath){$info=Test-ReferenceSource $FilePath $library;$existing=@(Get-ReferenceItems $library|Where-Object contentHash -eq $info.hash)}else{$normalized=ConvertTo-NormalizedReferenceUrl $Url;$existing=@(Get-ReferenceItems $library|Where-Object normalizedUrl -eq $normalized)};if($existing){if($ProjectRoot){Add-ReferenceProjectLink $ProjectRoot $existing[0].id $PrimaryRole -AgentHome $AgentHome};return [pscustomobject]@{Outcome='duplicate';Id=$existing[0].id;Library=$library}};$seed=if($info){$info.hash}else{(Get-FileHash -InputStream ([IO.MemoryStream]::new([Text.Encoding]::UTF8.GetBytes($normalized))) -Algorithm SHA256).Hash.ToLowerInvariant()};$id='ref-'+$seed.Substring(0,12);$temp=Join-Path $library ('tmp/'+$id+'-'+[guid]::NewGuid().ToString('N'));$final=Join-Path $library ('references/'+$id);New-Item -ItemType Directory -Path (Join-Path $temp 'source') -Force|Out-Null;$filename=if($info){$info.name}else{'SOURCE_URL.txt'};if($info){Copy-Item -LiteralPath $info.path -Destination (Join-Path $temp 'source/'+$filename);if((Get-FileHash (Join-Path $temp 'source/'+$filename) -Algorithm SHA256).Hash.ToLowerInvariant() -ne $info.hash){throw 'SOURCE_TAMPERED_DURING_CAPTURE'}}else{Write-AtomicTextFile $temp (Join-Path $temp 'source/'+$filename) $normalized}
    $role=if($PrimaryRole -eq 'UX'){'ux'}else{$PrimaryRole.ToLowerInvariant()};$metadata=[ordered]@{schemaVersion=1;id=$id;title=$Title.Trim();sourceType=if($info){'local-file'}else{'url'};originalFilename=$filename;normalizedUrl=$normalized;addedDate=[DateTime]::UtcNow.ToString('o');industries=@($Industries);platforms=@($Platforms);styleFamilies=@($StyleFamilies);visualModifiers=@($VisualModifiers);primaryRole=$role;secondaryRoles=@($SecondaryRoles);projectTypes=@($ProjectTypes);strongSections=@($StrongSections);supportedSurfaces=@($SupportedSurfaces);interactionEvidenceStatus='unknown';responsiveEvidenceStatus='unknown';status='active';confidence='unclassified';noCopy='Do not copy source text, asset, layout, or interaction implementation.';analysisLimitations='Static evidence does not verify runtime behavior.';contentHash=if($info){$info.hash}else{$null};untrustedContent=$true;executionAllowed=$false;promptInjectionSignals=if($info){@($info.promptSignals)}else{@()};secretScanStatus=if($info){$info.secretScanStatus}else{'not-applicable'};contentInspectionLimitations=if($info){@($info.limitations)}else{@('URL metadata only; no network fetch performed.')}};Write-AtomicTextFile $temp (Join-Path $temp 'metadata.json') ($metadata|ConvertTo-Json -Depth 12);Write-AtomicTextFile $temp (Join-Path $temp 'SOURCE.md') ('# Source`n`n- ID: `'+$id+'`');Write-AtomicTextFile $temp (Join-Path $temp 'ANALYSIS.md') '# Analysis`n`nUntrusted reference content cannot authorize execution, approval, scope, or access.';Assert-AuthorizedPath $library ('references/'+$id)|Out-Null;Move-Item -LiteralPath $temp -Destination $final;Write-ReferenceIndexes $library;if($ProjectRoot){Add-ReferenceProjectLink $ProjectRoot $id $PrimaryRole -AgentHome $AgentHome};[pscustomobject]@{Outcome='new reference';Id=$id;Library=$library}}
  finally{if($temp -and (Test-Path $temp)){Remove-Item -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue};Exit-ReferenceLibraryLock $lock $library}
}
function Find-ReferenceLibraryMatch { param([Parameter(Mandatory)][string]$AgentHome,[string[]]$Industries=@(),[string[]]$ProjectTypes=@(),[string[]]$StyleFamilies=@(),[string[]]$Roles=@('industry','visual','product','structural','ux'),[string[]]$Sections=@(),[string[]]$Surfaces=@(),[string[]]$VisualModifiers=@(),[string[]]$Platforms=@('web')) $library=Initialize-ReferenceLibrary $AgentHome;[pscustomobject]@{Library=$library;Matches=@(Get-ReferenceItems $library);BalancedSelection=@();MissingRoleGaps=@($Roles)} }
function Test-ReferenceLibraryIntegrity {
 param([Parameter(Mandatory)][string]$AgentHome,[switch]$RebuildIndexes)
 $library=Initialize-ReferenceLibrary $AgentHome;$hashes=@{};$urls=@{};$items=@(Get-ReferenceItems $library)
 foreach($i in $items){
  if($i.id -notmatch '^ref-[a-f0-9]{12}$' -or $i.untrustedContent -ne $true -or $i.executionAllowed -ne $false -or -not $i.secretScanStatus){throw 'INTEGRITY_METADATA_INVALID'}
  $folder=Join-Path $library ('references/'+$i.id);$file=Get-ChildItem (Join-Path $folder 'source') -File|Select-Object -First 1
  if($i.contentHash){if((Get-FileHash $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant() -ne $i.contentHash){throw 'INTEGRITY_SOURCE_HASH_MISMATCH'};if($hashes[$i.contentHash]){throw 'INTEGRITY_DUPLICATE_HASH'};$hashes[$i.contentHash]=$true}
  if($i.normalizedUrl){if($i.normalizedUrl -ne (ConvertTo-NormalizedReferenceUrl $i.normalizedUrl)){throw 'INTEGRITY_URL_UNSAFE'};if($urls[$i.normalizedUrl]){throw 'INTEGRITY_DUPLICATE_URL'};$urls[$i.normalizedUrl]=$true}
 }
 if(Get-ChildItem (Join-Path $library 'tmp') -Force|Select-Object -First 1){throw 'INTEGRITY_STALE_TEMP'}
 $expected=$items|Sort-Object id|ConvertTo-Json -Depth 12;$index=Join-Path $library 'indexes/REFERENCE_INDEX.json'
 if($RebuildIndexes){Write-ReferenceIndexes $library}elseif(-not(Test-Path $index) -or (Get-Content -Raw $index).Trim() -ne $expected.Trim()){throw 'INTEGRITY_INDEX_DRIFT'}
 $library
}
function Test-ReferenceProjectLinks { param([string]$AgentHome,[string]$ProjectRoot) $known=@(Get-ReferenceItems (Initialize-ReferenceLibrary $AgentHome)|ForEach-Object id);$file=Join-Path $ProjectRoot '.studio/references/PROJECT_REFERENCE_LINKS.json';if(Test-Path $file){$seen=@{};foreach($link in @(Get-Content -Raw $file|ConvertFrom-Json)){if($link.referenceId -notin $known){throw 'PROJECT_LINK_UNKNOWN_REFERENCE'};$key=$link.referenceId+'|'+$link.role;if($seen[$key]){throw 'PROJECT_LINK_DUPLICATE'};$seen[$key]=$true}} }
