[CmdletBinding()]
param([Parameter(Mandatory)][string]$ProjectRoot,[string]$OutputPath)
$ErrorActionPreference='Stop';. (Join-Path $PSScriptRoot 'records/Test-RequiredProjectRecords.ps1')
$project=(Resolve-Path -LiteralPath $ProjectRoot).Path;$req=Get-StudioRequirements $project;if(-not $req.state.valid){throw 'Cannot route specialists without valid machine-readable PROJECT_STATE.md.'};$d=$req.state.record.metadata.data;$s=@($req.surfaces);$risks=@($d.risks);$documentation=$s -contains 'documentation';$existing=(Test-Path (Join-Path $project 'package.json')) -or (Test-Path (Join-Path $project 'src'));$selected=[Collections.Generic.List[string]]::new();$skipped=[Collections.Generic.List[string]]::new();$reasons=[ordered]@{}
function Route([string]$role,[bool]$yes,[string]$why){if($yes){$selected.Add($role)}else{$skipped.Add($role)};$reasons[$role]=$why}
if($documentation){foreach($r in @('repo-explorer','frontend-builder','browser-qa','backend-builder','database-architect','integration-builder','test-engineer','code-reviewer','security-auditor','release-engineer','operations-engineer')){Route $r $false 'Documentation-only scope.'}}
else {$visible=$s -contains 'frontend-visible';$backend=$s -contains 'backend-api';$database=$s -contains 'database';$integration=$s -contains 'integration';$materialSecurity=@($s|Where-Object{$_ -in @('authentication','sensitive-data')}).Count -gt 0 -or @($risks|Where-Object{$_ -match '(?i)(auth|secret|sensitive|security|webhook)'}).Count -gt 0;$operations=@($s|Where-Object{$_ -in @('server-job','operations')}).Count -gt 0 -or @($risks|Where-Object{$_ -match '(?i)(uptime|incident|backup|recovery|persistent production)'}).Count -gt 0;$release=$s -contains 'release';Route 'repo-explorer' ($existing -and (@($d.unknownBoundaries).Count -gt 0)) $(if($existing){'Existing repository with unknown boundaries.'}else{'No unknown repository boundary.'});Route 'frontend-builder' $visible $(if($visible){'frontend-visible is active.'}else{'No visible frontend surface.'});Route 'backend-builder' $backend $(if($backend){'backend-api is active.'}else{'No backend API surface.'});Route 'database-architect' $database $(if($database){'database is active.'}else{'No database surface.'});Route 'integration-builder' $integration $(if($integration){'integration is active.'}else{'No integration surface.'});$implementation=$visible -or $backend -or $database -or $integration;Route 'test-engineer' $implementation $(if($implementation){'Executable implementation surface is active.'}else{'No executable implementation surface.'});Route 'code-reviewer' $implementation $(if($implementation){'Implementation surface needs review.'}else{'No implementation surface.'});Route 'security-auditor' $materialSecurity $(if($materialSecurity){'Material security risk.'}else{'No material security risk.'});Route 'browser-qa' ($visible -and [bool]$d.runnable) $(if($visible -and $d.runnable){'Visible runnable surface.'}elseif($visible){'Visible surface is not runnable; browser verification is deferred.'}else{'No visible frontend surface.'});Route 'release-engineer' $release $(if($release){'Explicit release surface.'}else{'No release surface.'});Route 'operations-engineer' $operations $(if($operations){'Explicit persistent runtime/operations risk.'}else{'Database alone does not imply operations.'})}
$plan=[ordered]@{schemaVersion=1;selected=@($selected);skipped=@($skipped);reasons=$reasons;surfaces=@($s);risks=@($risks);executionOrder=@($selected);ownershipConflicts=@();browserVerification=if(($s -contains 'frontend-visible') -and -not $d.runnable){'deferred: surface is not runnable'}else{''}}
if($OutputPath){$dir=Split-Path -Parent $OutputPath;New-Item -ItemType Directory -Force -Path $dir|Out-Null;$plan|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $OutputPath -Encoding utf8;($plan|ConvertTo-Json -Depth 8)|Set-Content -LiteralPath ($OutputPath -replace '\.json$','.md') -Encoding utf8};[pscustomobject]$plan
