[CmdletBinding()]
param([Parameter(Mandatory)][string]$ProjectRoot,[string]$OutputPath)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'records/Test-RequiredProjectRecords.ps1')
. (Join-Path $PSScriptRoot 'records/RecordValidationHelpers.ps1')
. (Join-Path $PSScriptRoot 'security/Test-ProjectRelativePath.ps1')
$project=(Resolve-Path -LiteralPath $ProjectRoot).Path;$studio=Join-Path $project '.studio';$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$req=Get-StudioRequirements $project
if(-not $req.state.valid){throw 'Cannot route specialists without valid machine-readable PROJECT_STATE.md.'}
$d=$req.state.record.metadata.data;$surfaces=@($req.surfaces);$registry=(Get-Content -Raw (Join-Path $root 'specialists/SPECIALIST_REGISTRY.json')|ConvertFrom-Json).specialists;$planRecord=Test-StudioRecord -Path (Join-Path $studio 'IMPLEMENTATION_PLAN.md') -ExpectedRecordType 'implementation-plan' -Required;$tasks=@($planRecord.record.metadata.data.tasks);$criteria=@((Test-StudioRecord -Path (Join-Path $studio 'ACCEPTANCE_CRITERIA.md') -ExpectedRecordType 'acceptance-criteria' -Required).record.metadata.data.criteria)
$existing=(Test-Path (Join-Path $project 'package.json')) -or (Test-Path (Join-Path $project 'src'));$mapPath=Join-Path $studio 'REPO_MAP.json';$map=if(Test-Path $mapPath){Get-Content -Raw $mapPath|ConvertFrom-Json}else{$null};$mapUnknown=if($map -and $map.PSObject.Properties['unknowns']){@($map.unknowns)}else{@()};$stateUnknown=if($d.PSObject.Properties['unknownBoundaries']){@($d.unknownBoundaries)}else{@()};$unknown=@($mapUnknown)+@($stateUnknown);$selected=[Collections.Generic.List[string]]::new();$reasons=[ordered]@{}
function Select-Role($role,$reason){if($selected -notcontains $role){$selected.Add($role)};$reasons[$role]=$reason}
$docOnly=($surfaces.Count -eq 1 -and $surfaces -contains 'documentation');$implementation=@($surfaces|Where-Object{$_ -in @('frontend-visible','frontend-nonvisual','backend-api','server-job','database','integration','approved-refactor')}).Count -gt 0;$persistentJob=if($d.PSObject.Properties['persistentProductionJob']){[bool]$d.persistentProductionJob}else{$false};$productionOperated=if($d.PSObject.Properties['productionOperated']){[bool]$d.productionOperated}else{$false};$approvedRemediation=if($d.PSObject.Properties['approvedStructuralRemediation']){[bool]$d.approvedStructuralRemediation}else{$false};$measurablePerformance=if($d.PSObject.Properties['measurablePerformanceCriterion']){[bool]$d.measurablePerformanceCriterion}else{$false};$knownRegression=if($d.PSObject.Properties['knownPerformanceRegression']){[bool]$d.knownPerformanceRegression}else{$false}
if($existing -and @($unknown).Count){Select-Role 'repo-explorer' 'Repository map contains unresolved boundaries.'}
if(-not $docOnly){if($surfaces -contains 'frontend-visible' -or $surfaces -contains 'frontend-nonvisual'){Select-Role 'frontend-builder' 'Frontend surface is active.'};if($surfaces -contains 'backend-api' -or (($surfaces -contains 'server-job') -and ($persistentJob -or $productionOperated)) -or (($surfaces -contains 'authentication') -and $implementation)){Select-Role 'backend-builder' 'Backend or authentication implementation is active.'};if($surfaces -contains 'database'){Select-Role 'database-architect' 'Database surface is active.'};if($surfaces -contains 'integration'){Select-Role 'integration-builder' 'Integration surface is active.'};if($surfaces -contains 'approved-refactor' -or $approvedRemediation){Select-Role 'refactor-engineer' 'Approved refactor or structural remediation is active.'};if($implementation){Select-Role 'test-engineer' 'Implementation requires tests.';Select-Role 'code-reviewer' 'Implementation requires review.'};if(@($surfaces|Where-Object{$_ -in @('authentication','sensitive-data')}).Count -or @($d.risks|Where-Object{$_ -match '(?i)(security|secret|webhook|auth)'}).Count){Select-Role 'security-auditor' 'Material security surface or risk is active.'};if(($surfaces -contains 'performance') -or $measurablePerformance -or $knownRegression){Select-Role 'performance-auditor' 'Measurable performance work is active.'};if(($surfaces -contains 'frontend-visible') -and [bool]$d.runnable){Select-Role 'browser-qa' 'Visible runnable surface needs browser evidence.'};if($surfaces -contains 'release'){Select-Role 'release-engineer' 'Release surface is active.'};if(($surfaces -contains 'operations') -or (($surfaces -contains 'server-job') -and ($persistentJob -or $productionOperated))){Select-Role 'operations-engineer' 'Persistent runtime or operations is active.'}}
$edges=[Collections.Generic.List[object]]::new();function Edge($from,$to,$reason){if(($selected -contains $from) -and ($selected -contains $to)){$edges.Add([ordered]@{from=$from;to=$to;reason=$reason})}}
Edge 'repo-explorer' 'frontend-builder' 'Unknown boundaries precede implementation.';Edge 'repo-explorer' 'backend-builder' 'Unknown boundaries precede implementation.';Edge 'database-architect' 'backend-builder' 'Database decisions precede persistence writes.';Edge 'backend-builder' 'test-engineer' 'Implementation precedes tests.';Edge 'frontend-builder' 'test-engineer' 'Implementation precedes tests.';Edge 'integration-builder' 'test-engineer' 'Implementation precedes tests.';Edge 'test-engineer' 'code-reviewer' 'Tests precede final review.';Edge 'frontend-builder' 'browser-qa' 'Visible implementation precedes browser QA.';Edge 'test-engineer' 'release-engineer' 'Tests precede release.';Edge 'code-reviewer' 'release-engineer' 'Review precedes release.';Edge 'release-engineer' 'operations-engineer' 'Release intent precedes operations readiness.'
$nodes=@();$assignRoot=Join-Path $studio 'runtime/assignments';New-Item -ItemType Directory -Force -Path $assignRoot|Out-Null;foreach($role in $selected){$spec=$registry|Where-Object id -eq $role;$roleTasks=@($tasks|Where-Object{$_.owner -eq $role -or @($_.surfaces|Where-Object{$spec.surfaces -contains $_}).Count});$paths=@($roleTasks|ForEach-Object affectedPaths|Select-Object -Unique);$mode=[string]$spec.mode;$blocked=@();if($mode -eq 'write' -and [bool]$spec.requiresAssignedWritePaths -and $paths.Count -eq 0){$blocked+='WRITE_ROLE_WITHOUT_ALLOWED_PATH'};foreach($path in $paths){$pathCheck=Test-ProjectRelativePath $project $path -AllowGlob;if(-not $pathCheck.valid){$blocked+='INVALID_ALLOWED_PATH'}};$pred=@($edges|Where-Object to -eq $role|ForEach-Object from);$group=if($mode -eq 'read'){3}elseif($pred.Count){2}else{1};$assignment=[ordered]@{schemaVersion=1;role=$role;taskIds=@($roleTasks|ForEach-Object id);criteriaIds=@($roleTasks|ForEach-Object acceptanceCriteria|Select-Object -Unique);surfaces=@($surfaces|Where-Object{$spec.surfaces -contains $_});allowedPaths=$paths;forbiddenPaths=@('.git/**','.env*','.studio/**');requiredRecords=@($spec.requiredRecords|ForEach-Object{'.studio/'+$_});ruleIds=@();commands=@();predecessors=$pred;parallelGroup=$group;maxRemediationLoops=(Get-RemediationLoopLimit $d.workflowMode);status=if($blocked.Count){'blocked'}else{'ready'}};$assignment|ConvertTo-Json -Depth 12|Set-Content (Join-Path $assignRoot ($role+'.json')) -Encoding utf8;$nodes+=[ordered]@{id=$role;mode=$mode;taskIds=$assignment.taskIds;criteriaIds=$assignment.criteriaIds;predecessors=$pred;parallelGroup=$group;allowedPaths=$paths;requiredRecords=$assignment.requiredRecords;reason=$reasons[$role];status=$assignment.status}}
$plan=[ordered]@{schemaVersion=2;status=if(@($nodes|Where-Object status -eq 'blocked').Count){'blocked'}else{'ready'};nodes=$nodes;edges=@($edges);ownershipConflicts=@();blockedReasons=@($nodes|Where-Object status -eq 'blocked'|ForEach-Object id);surfaces=$surfaces;workflowMode=$d.workflowMode;selected=@($selected);executionOrder=@($selected);reasons=$reasons;skipped=@()}
if($OutputPath){New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputPath)|Out-Null;$plan|ConvertTo-Json -Depth 16|Set-Content $OutputPath -Encoding utf8};[pscustomobject]$plan
