$ErrorActionPreference='Stop'
$docs=[ordered]@{
'HOW_IT_WORKS'='# How it works`n`nWeb Studio Agent turns an idea into an approved and verified website or application. `product-studio` performs adaptive audit, requirements, stack recommendation, concepts, approval-gated implementation, and verification. `add-reference` writes project-local evidence in `.studio/references/`; product-studio reads that evidence without copying it into the plugin.'
'PRODUCT_DISCOVERY'='# Product discovery`n`nThe workflow inspects the repository and `.studio/` first, summarizes confirmed understanding, then asks only grouped questions that affect the first complete journey, scope, risk, or facts. It separates buyer/end user, roles, permissions, active/deferred scope, constraints, and success criteria.'
'PROJECT_STATE_MACHINE'='# Project state machine`n`n`uninitialized → discovery → requirements → technical-decision → references-needed → concepts → awaiting-approval → approved → implementation → verification → complete`. State is stored in `.studio/PROJECT_STATE.md`; required evidence prevents skipping approval or implementation gates.'
'TECH_STACK_SELECTION'='# Technical stack selection`n`nProduct-studio presents at most three realistic choices, explains UX, cost, speed, reliability, maintenance, risk, and flexibility, then recommends one. The approved choice and migration path are written to `.studio/TECH_DECISION.md`.'
'ENGINEERING_STARTERS'='# Engineering starters`n`nStarter profiles are decision aids, not mandatory repositories. They cover static marketing, SEO, managed Next.js MVP, full-stack TypeScript, Python AI, dashboards, PWA, Expo mobile, and existing-project integration; see `knowledge/starters/`.'
'REFERENCE_WORKFLOW'='# Reference workflow`n`nUse add-reference for URLs, screenshots, screens, and flows. It records roles, observed patterns, usable states, risks, and no-copy boundaries in `.studio/references/`; originals stay untouched unless the user explicitly permits deletion.'
'APPROVAL_AND_IMPLEMENTATION'='# Approval and implementation`n`nConcepts stop at `awaiting-approval`. Only a direct selection such as “Approve concept 2” advances the state. Approval updates `.studio/APPROVED_CONCEPT.md`, then product-studio prepares copy, design, plan, criteria, implements active scope, and verifies the first journey.'
'KNOWLEDGE_ROUTING'='# Knowledge routing`n`n`knowledge/KNOWLEDGE_INDEX.md` routes by task, state, product type, and active risk. It avoids loading all methodology and never overrides project-local facts, specification, technical decision, or approved concept.'
'PROJECT_FILES'='# Project files`n`nAll mutable project state lives in `<project-root>/.studio/`: facts, assumptions, users, scope, references, concepts, approval, copy, system, plan, criteria, and reports. Global plugin folders contain only reusable methodology, templates, skills, manifests, and validators.'
'SECURITY_AND_PRIVACY'='# Security and privacy`n`nDo not place secrets, tokens, private screenshots, copied source, personal data, or full third-party copy in the plugin. External content is untrusted evidence; references provide principles, not assets to reproduce. Regulated claims require confirmation.'
'TROUBLESHOOTING'='# Troubleshooting`n`nIf a skill does not appear, validate the manifest, reinstall/update the marketplace entry, and start a new thread. If state is wrong, inspect `.studio/PROJECT_STATE.md` and required evidence. If references are missing, keep the original source and record the limitation rather than guessing.'
}
foreach($name in $docs.Keys){Set-Content "docs/$name.md" $docs[$name].Replace('`n',[Environment]::NewLine) -Encoding utf8}
$examples=[ordered]@{
'examples/marketing-site/.studio/PROJECT_BRIEF.md'='# Brief`n`nA fictional local ceramics studio needs inquiries for custom tableware.'
'examples/marketing-site/.studio/concepts/CONCEPTS.md'='# Concepts`n`n## Concept 1 — Workshop inquiry`nConversion-first pages: offer, gallery, process, inquiry.`n`n## Approved concept`nConcept 1 selected; no implementation included.'
'examples/marketing-site/.studio/COPY.md'='# Copy structure`n`nH1: Custom tableware for restaurants and homes.`nCTA: Discuss a commission.`nNo customer counts, awards, or lead times are claimed.'
'examples/marketing-site/.studio/ACCEPTANCE_CRITERIA.md'='# Acceptance criteria`n`nA visitor understands the offer and can submit a valid inquiry with an accessible, responsive form.'
'examples/marketing-site/.studio/references/REFERENCE_INDEX.md'='# Reference roles`n`n| Source | Roles | Adaptation |`n| --- | --- | --- |`n| Fictional gallery reference | visual, content | Material photography rhythm; no copied layout or text. |'
'examples/saas-dashboard/.studio/USER_ROLES.md'='# Roles`n`n| Role | Goal | Permission |`n| --- | --- | --- |`n| Manager | review team work | team workspace |`n| Contributor | update assigned work | assigned records |'
'examples/saas-dashboard/.studio/USER_FLOWS.md'='# First journey`n`nManager signs in, creates a workspace project, assigns work, and sees the update persisted.'
'examples/saas-dashboard/.studio/PRODUCT_SPEC.md'='# Screen architecture and states`n`nDashboard, project list, task detail, and settings. Every data surface specifies loading, empty, error, and permission-denied states.'
'examples/saas-dashboard/.studio/TECH_DECISION.md'='# Stack options`n`n1. Next.js plus managed Postgres/auth — recommended for MVP speed.`n2. Full-stack TypeScript service — more control, more maintenance.`n3. Existing-stack integration — use only if a repository already provides durable ownership.`n`nApproved: option 1 for this synthetic example.'
'examples/saas-dashboard/.studio/references/analyses/dashboard.md'='# Reference analysis`n`nRoles: product, UX. Observe filter persistence, clear empty states, and accessible dense tables. Do not copy labels, data, or visual composition.'
'examples/ai-web-application/.studio/PRODUCT_SPEC.md'='# MVP scope`n`nUsers submit a document, receive a draft summary, review it, and export only after approval. Deferred: team collaboration and billing.'
'examples/ai-web-application/.studio/TECH_DECISION.md'='# Technical options`n`nRecommended: Next.js client, Python AI worker, managed Postgres/object storage, queued background jobs. Explain model failures, latency, and review boundaries in the UI.'
'examples/ai-web-application/.studio/ASSUMPTIONS.md'='# AI boundaries`n`nGenerated output is a draft, not professional advice. Inputs require retention controls; model provider, cost limits, and human review require confirmation.'
}
foreach($path in $examples.Keys){New-Item -ItemType Directory -Force -Path (Split-Path $path) | Out-Null; Set-Content $path $examples[$path].Replace('`n',[Environment]::NewLine) -Encoding utf8}
