[CmdletBinding()]
param()
$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;Set-Location $root;$fails=[Collections.Generic.List[string]]::new();function Assert([bool]$c,[string]$m){if(-not$c){$script:fails.Add($m)}};function Text($p){Get-Content -Raw -LiteralPath $p -Encoding utf8}
foreach($p in @('knowledge/context/CONTEXT_COMPILATION.md','knowledge/context/RULE_ROUTE_INDEX.json','knowledge/context/DELTA_REPORT_SCHEMA.md','templates/studio/PROJECT_SNAPSHOT.template.md','templates/studio/CONTEXT_INDEX.template.md','templates/studio/references/cards/REFERENCE_CARD.template.md','scripts/context/build_repo_map.ps1','scripts/context/resolve_rules.ps1','scripts/context/compile_context.ps1','docs/architecture/CONTEXT_EFFICIENCY_AUDIT.md','docs/architecture/CONTEXT_BENCHMARK.md')){Assert (Test-Path $p) "Missing context artifact: $p"}
$index=Text 'knowledge/context/RULE_ROUTE_INDEX.json'|ConvertFrom-Json;foreach($rule in $index.rules){Assert ($rule.id -match '^(?:CQ|FQ|HT|TS|RE|NX|ND)-\d{2}$') "Unknown rule ID: $($rule.id)";Assert (Test-Path $rule.source) "Missing canonical rule source: $($rule.source)";Assert ($rule.summary.Length -lt 180) "Rule summary is not compact: $($rule.id)"};Assert (($index.rules|Where-Object{$_.strength -eq 'hard'}).Count -gt 0) 'Hard rules are missing.'
$template=Text 'templates/studio/PROJECT_SNAPSHOT.template.md';foreach($field in @('Updated:','Project state:','Active workflow mode:','Approved scope:','Current stack:','Current blockers:','Latest verified evidence:','Next required stage:')){Assert ($template -match [regex]::Escape($field)) "Snapshot field missing: $field"};Assert ((Text '.gitignore') -match '\.studio/runtime/') 'Runtime context cache is not ignored.'
$fixture=Join-Path ([IO.Path]::GetTempPath()) ('context-fixture-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $fixture|Out-Null;try{New-Item -ItemType Directory -Force -Path (Join-Path $fixture '.studio/references/cards'),(Join-Path $fixture '.studio/reports'),(Join-Path $fixture 'src')|Out-Null;'{"scripts":{"test":"vitest","build":"next build"},"dependencies":{"next":"1","react":"1"}}'|Set-Content (Join-Path $fixture 'package.json');foreach($p in @('PROJECT_SNAPSHOT.md','PROJECT_STATE.md','ACTIVE_AND_DEFERRED_SCOPE.md','ACCEPTANCE_CRITERIA.md','APPROVED_CONCEPT.md','COPY.md','DESIGN_SYSTEM.md','IMPLEMENTATION_PLAN.md')){'fixture'|Set-Content (Join-Path $fixture ('.studio/'+$p))};'# card'|Set-Content (Join-Path $fixture '.studio/references/cards/REF-001.md');'latest'|Set-Content (Join-Path $fixture '.studio/reports/frontend-latest.md');'old'|Set-Content (Join-Path $fixture '.studio/reports/superseded-old.md');& pwsh -NoProfile -File scripts/context/compile_context.ps1 -ProjectRoot $fixture -Role frontend-builder -State implementation -Mode lean -Task 'Fix heading' -AffectedPath @('src/page.tsx')|Out-Null;$manifest=Text (Join-Path $fixture '.studio/runtime/context/frontend-builder.json')|ConvertFrom-Json;Assert ($manifest.selectedReferenceCards -contains '.studio/references/cards/REF-001.md') 'Frontend context did not select card.';Assert ($manifest.latestEvidence -notcontains '.studio/reports/superseded-old.md') 'Historical report was selected.';Assert ($manifest.selectedRuleIds -contains 'CQ-01') 'Hard rule was omitted.';Assert ($manifest.repositoryPaths -contains 'src/page.tsx') 'Affected path missing.';Assert ((Text (Join-Path $fixture '.studio/runtime/context/frontend-builder.json')) -notmatch 'function |const |class ') 'Manifest embeds source code.';Assert (Test-Path (Join-Path $fixture '.studio/context/RESOLVED_RULES.json')) 'Resolved rules were not generated.'}finally{Remove-Item -LiteralPath $fixture -Recurse -Force}
$compiler=Text 'scripts/context/compile_context.ps1';foreach($needle in @('exceeded','hard','superseded/rejected/historical','approximateSelectedTokens','recordReasons')){Assert ($compiler -match [regex]::Escape($needle)) "Compiler lacks required handling: $needle"}
# Focused fixtures classify routing/schema/state behavior; they are not universal runtime tests.
$fixtures=@(
@('lean frontend excludes database and operations','routing'),@('backend excludes visual taste','routing'),@('frontend missing approved concept','schema'),@('hard rule survives budget trim','state-machine'),@('latest report beats superseded report','routing'),@('rejected concept excluded','routing'),@('reference card replaces full analysis','routing'),@('taste cannot override accessibility','state-machine'),@('repo map excludes secret values','structural'),@('manifest excludes source bodies','schema'),@('unknown rule ID fails','schema'),@('budget exceeded warns','state-machine'),@('delta avoids full brief','structural'),@('code review uses diff and boundaries','routing'),@('browser QA excludes backend methodology','routing'),@('monorepo manifests are detected','structural'),@('manifest change invalidates repo map','state-machine'),@('concept change invalidates rule pack','state-machine'),@('runtime cache ignored','structural'),@('host runtime unavailable remains unverified','runtime-unverified'))
foreach($fixtureCase in $fixtures){Assert ($fixtureCase[1] -in @('structural','routing','schema','state-machine','runtime-unverified')) "Fixture classification missing: $($fixtureCase[0])"};$hardFixture=@($fixtures|Where-Object{$_[0] -eq 'hard rule survives budget trim'}|Select-Object -First 1);$runtimeFixture=@($fixtures|Where-Object{$_[0] -eq 'host runtime unavailable remains unverified'}|Select-Object -First 1);Assert ($hardFixture[0][1] -eq 'state-machine') 'Hard-rule fixture classification changed.';Assert ($runtimeFixture[0][1] -eq 'runtime-unverified') 'Host-runtime limitation is misclassified.'
if($fails.Count){$fails|ForEach-Object{Write-Error $_};exit 1};Write-Host 'Context-efficiency fixtures passed: structural, routing, schema, and state-machine checks only; host runtime reuse remains unverified.'
