$ErrorActionPreference='Stop';. (Join-Path $PSScriptRoot 'ReferenceLibrary.ps1')
$root=Join-Path ([IO.Path]::GetTempPath()) ('reference-security-'+[guid]::NewGuid());New-Item -ItemType Directory -Path $root|Out-Null
try{
 $firstFile=Join-Path $root 'first-safe.txt';$secondFile=Join-Path $root 'second-safe.txt';[IO.File]::WriteAllText($firstFile,'first safe reference');[IO.File]::WriteAllText($secondFile,'second safe reference');$libraryHome=Join-Path $root 'home';$project=Join-Path $root 'project';New-Item -ItemType Directory -Path $project|Out-Null;$first=Add-ReferenceLibraryItem -AgentHome $libraryHome -FilePath $firstFile -Title 'First reference' -ProjectRoot $project;$second=Add-ReferenceLibraryItem -AgentHome $libraryHome -FilePath $secondFile -Title 'Second reference' -ProjectRoot $project;if($first.Outcome -ne 'new reference' -or $second.Outcome -ne 'new reference'){throw 'different source files were not ingested'};if($first.Id -eq $second.Id){throw 'different hashes produced one reference ID'};$linksFile=Join-Path $project '.studio/references/PROJECT_REFERENCE_LINKS.json';$linksRaw=Get-Content -Raw $linksFile;if(-not $linksRaw.TrimStart().StartsWith('[')){throw 'project links are not serialized as an array'};$links=@($linksRaw|ConvertFrom-Json);if($links.Count -ne 2){throw 'project link count should remain two after two different sources'};$linkIds=@($links|ForEach-Object referenceId);if($first.Id -notin $linkIds -or $second.Id -notin $linkIds){throw 'project links are missing returned reference IDs'};$firstAgain=Add-ReferenceLibraryItem -AgentHome $libraryHome -FilePath $firstFile -ProjectRoot $project;if($firstAgain.Outcome -ne 'duplicate'){throw 'hash dedup failed'};$links=@(Get-Content -Raw $linksFile|ConvertFrom-Json);if($links.Count -ne 2){throw 're-adding the first source changed the project link count'};$projectIndex=Get-Content -Raw (Join-Path $project '.studio/references/PROJECT_REFERENCE_INDEX.md');if($projectIndex -notmatch [regex]::Escape($first.Id) -or $projectIndex -notmatch [regex]::Escape($second.Id)){throw 'project index is missing reference IDs'};if($projectIndex.Contains('`n')){throw 'project index contains literal backtick-n sequences'};if($projectIndex -notmatch "[`r`n]"){throw 'project index does not contain real newline characters'}
 $url=Add-ReferenceLibraryItem -AgentHome $libraryHome -Url 'HTTPS://example.com/a?utm_source=x&token=hidden&z=1#fragment';$meta=Get-ReferenceItems (Initialize-ReferenceLibrary $libraryHome)|Where-Object id -eq $url.Id;if($meta.normalizedUrl -match 'token|utm'){throw 'sensitive URL persisted'}
 foreach($bad in @('.env','x.ps1','x.sql')){$p=Join-Path $root $bad;[IO.File]::WriteAllText($p,'x');try{Add-ReferenceLibraryItem -AgentHome $libraryHome -FilePath $p;throw "unsafe source accepted: $bad"}catch{if($_.Exception.Message -notmatch 'SOURCE_'){throw}}}
 Test-ReferenceLibraryIntegrity -AgentHome $libraryHome|Out-Null
}finally{Remove-Item $root -Recurse -Force -ErrorAction SilentlyContinue}
Write-Host 'Reference security tests passed.'
