[CmdletBinding()]param()
$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$work=Join-Path ([IO.Path]::GetTempPath()) ('web-studio-phase4-'+[guid]::NewGuid().ToString('N'));$agentHome=Join-Path $work 'agent-home';New-Item -ItemType Directory -Force $work|Out-Null
. (Join-Path $PSScriptRoot 'ReferenceLibrary.ps1')
function Expect-Failure([scriptblock]$Action,[string]$Name){try{&$Action;throw "Expected failure: $Name"}catch{if($_.Exception.Message -match '^Expected failure:'){throw};Write-Host "Expected failure: $Name"}}
function New-Project([string]$Name,[string]$State){$project=Join-Path $work $Name;$studio=Join-Path $project '.studio';New-Item -ItemType Directory -Force $studio|Out-Null;foreach($record in @('PROJECT_BRIEF','CONFIRMED_FACTS','ASSUMPTIONS','TECH_DECISION','APPROVED_CONCEPT','COPY','DESIGN_SYSTEM','IMPLEMENTATION_PLAN','ACCEPTANCE_CRITERIA')){"# $record"|Set-Content (Join-Path $studio "$record.md")};$State|Set-Content (Join-Path $studio 'PROJECT_STATE.md');$project}
function Init([string]$Project){& (Join-Path $root 'scripts/Initialize-ApprovedProjectRecords.ps1') -ProjectRoot $Project|Out-Null; 'Owner: fixture; configured backup: unverified; restore test evidence: not run.'|Set-Content (Join-Path $Project '.studio/OPERATIONS_PLAN.md')}
try {
  # Packaging/schema: this is a structural package audit, not a host install.
  $codex=Get-Content -Raw (Join-Path $root '.codex-plugin/plugin.json')|ConvertFrom-Json;$claude=Get-Content -Raw (Join-Path $root '.claude-plugin/plugin.json')|ConvertFrom-Json
  if($codex.skills -ne './skills/' -or $codex.name -ne 'web-studio-agent' -or $claude.name -ne 'web-studio-agent'){throw 'Plugin manifests are invalid.'}
  $skills=@(Get-ChildItem (Join-Path $root 'skills') -Recurse -Filter SKILL.md);if($skills.Count -ne 2){throw 'Package exposes other than two user-facing skills.'}
  foreach($path in @('templates/studio','knowledge','platforms/codex/agents','platforms/claude/agents','scripts/validate_migration.ps1')){if(-not(Test-Path (Join-Path $root $path))){throw "Required distributable path missing: $path"}}
  $ignore=Get-Content -Raw (Join-Path $root '.gitignore');foreach($rule in @('.studio/','.studio-phase4/','.env','.env.*','backups/','.phase1-test-output/','.phase2-test-output/','.phase3-test-output/')){if($ignore -notmatch [regex]::Escape($rule)){throw "Package hygiene ignore missing: $rule"}}
  $active=@('skills','knowledge','templates','.codex-plugin','.claude-plugin','platforms')|ForEach-Object{Get-ChildItem (Join-Path $root $_) -Recurse -File};foreach($file in $active){$text=Get-Content -Raw $file.FullName;if($text -match '(?i)(?:[a-z]:[\\/](?:Users|Documents|Desktop|AppData)[\\/]|/(?:Users|home)/)'){throw "Absolute local machine path in distributable file: $($file.FullName)"}}
  # Isolated static/lead/SaaS routing and preflight proof; no agent/chat runtime is implied.
  $static=New-Project 'static' '- Product type: static landing';& (Join-Path $root 'scripts/Test-ImplementationPreflight.ps1') -ProjectRoot $static;$staticPlan=& (Join-Path $root 'scripts/Resolve-SpecialistPlan.ps1') -ProjectRoot $static;if($staticPlan.Selected -contains 'database-architect' -or $staticPlan.Selected -contains 'operations-engineer'){throw 'Static workflow selected database or operations.'}
  $lead=New-Project 'lead' "- Backend required: yes`n- External integration required: yes";Expect-Failure {& (Join-Path $root 'scripts/Test-ImplementationPreflight.ps1') -ProjectRoot $lead} 'lead requires backend/integration/security records';Init $lead;& (Join-Path $root 'scripts/Test-ImplementationPreflight.ps1') -ProjectRoot $lead;$leadPlan=& (Join-Path $root 'scripts/Resolve-SpecialistPlan.ps1') -ProjectRoot $lead;foreach($role in @('frontend-builder','backend-builder','integration-builder','security-auditor','test-engineer','code-reviewer','browser-qa')){if($leadPlan.Selected -notcontains $role){throw "Lead routing missing $role"}};if($leadPlan.Selected -contains 'database-architect'){throw 'Lead routing incorrectly selected database.'}
  $saas=New-Project 'saas' "- Backend required: yes`n- Persistence required: yes`n- Authentication required: yes`n- External integration required: yes`n- Production SaaS handoff";Expect-Failure {& (Join-Path $root 'scripts/Test-ImplementationPreflight.ps1') -ProjectRoot $saas} 'SaaS requires technical and operations records';Init $saas;& (Join-Path $root 'scripts/Test-ImplementationPreflight.ps1') -ProjectRoot $saas;$saasPlan=& (Join-Path $root 'scripts/Resolve-SpecialistPlan.ps1') -ProjectRoot $saas;foreach($role in @('database-architect','backend-builder','integration-builder','security-auditor','release-engineer','operations-engineer')){if($saasPlan.Selected -notcontains $role){throw "SaaS routing missing $role"}}
  # Release gate: a build never supplies deployment evidence.
  $release=New-Project 'release' '- Release required: yes';Init $release;'production complete; build succeeded'|Set-Content (Join-Path $release '.studio/RELEASE_PLAN.md');Expect-Failure {& (Join-Path $root 'scripts/Test-ImplementationPreflight.ps1') -ProjectRoot $release} 'release claim without deployment evidence';'Deployment evidence: local release simulation only'|Set-Content (Join-Path $release '.studio/DEPLOYMENT_VERIFICATION.md');& (Join-Path $root 'scripts/Test-ImplementationPreflight.ps1') -ProjectRoot $release
  # Cross-project reference reuse, including both deterministic duplicate modes.
  $roles=@('industry','visual','product','structural','UX');$ids=@();foreach($role in $roles){$referenceFile=Join-Path $work ("reference-$role.txt");"phase4 reference $role"|Set-Content $referenceFile;$added=Add-ReferenceLibraryItem -AgentHome $agentHome -FilePath $referenceFile -Title "Reference $role" -Industries "industry-$role" -ProjectTypes saas -StyleFamilies "style-$role" -PrimaryRole $role -StrongSections hero;$ids+=$added.id};if($ids.Count -ne 5){throw 'Library did not ingest five role-diverse references'};$exact=Add-ReferenceLibraryItem -AgentHome $agentHome -FilePath (Join-Path $work 'reference-industry.txt');if($exact.Outcome -ne 'exact duplicate' -or $exact.id -ne $ids[0]){throw 'Exact duplicate did not preserve stable ID'};$urlOne=Add-ReferenceLibraryItem -AgentHome $agentHome -Url 'https://example.test/demo/#fragment' -Title 'URL reference' -PrimaryRole visual;$urlTwo=Add-ReferenceLibraryItem -AgentHome $agentHome -Url 'HTTPS://EXAMPLE.TEST/demo';if($urlTwo.Outcome -ne 'normalized URL duplicate'){throw 'Normalized URL duplicate failed'};Test-ReferenceLibraryIntegrity -AgentHome $agentHome|Out-Null;Add-ReferenceProjectLink -ProjectRoot $static -ReferenceId $urlOne.id -Role visual;Test-ReferenceProjectLinks -AgentHome $agentHome -ProjectRoot $static
  Write-Host 'Phase 4 structural integration passed: package schema, isolated routing/preflight, release gate, and reference reuse.'
} finally {if(Test-Path $work){Remove-Item -LiteralPath $work -Recurse -Force}}
