[CmdletBinding()]param()
$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$work=Join-Path ([IO.Path]::GetTempPath()) ('web-studio-phase3-'+[guid]::NewGuid().ToString('N'));$libraryHome=Join-Path $work 'library-home';New-Item -ItemType Directory -Force $work|Out-Null
. (Join-Path $PSScriptRoot 'ReferenceLibrary.ps1')
function Expect-Failure([scriptblock]$Action,[string]$Name){try{&$Action;throw "Expected failure: $Name"}catch{if($_.Exception.Message -match '^Expected failure:'){throw};Write-Host "Expected failure: $Name"}}
function New-Project([string]$Name,[string]$State){$p=Join-Path $work $Name;$s=Join-Path $p '.studio';New-Item -ItemType Directory -Force $s|Out-Null;foreach($n in @('PROJECT_BRIEF','CONFIRMED_FACTS','ASSUMPTIONS','TECH_DECISION','APPROVED_CONCEPT','COPY','DESIGN_SYSTEM','IMPLEMENTATION_PLAN','ACCEPTANCE_CRITERIA')){"# $n"|Set-Content (Join-Path $s "$n.md")};$State|Set-Content (Join-Path $s 'PROJECT_STATE.md');$p}
function Init-Phase3([string]$Project){& (Join-Path $root 'scripts/Initialize-ApprovedProjectRecords.ps1') -ProjectRoot $Project|Out-Null;$s=Join-Path $Project '.studio';'Affected files: src/a.ts; ownership: frontend-builder temporary transfer; regression test; rollback: revert approved commit.'|Set-Content (Join-Path $s 'REFACTOR_PLAN.md');'| Behavior | Evidence | Owner |`n| --- | --- | --- |`n| existing journey | regression | test-engineer |'|Set-Content (Join-Path $s 'BEHAVIOR_INVARIANTS.md');'Owner: ops; restore test evidence: not run; configured backup: unknown'|Set-Content (Join-Path $s 'OPERATIONS_PLAN.md')}
try {
  # M: source refactor evidence is mandatory; N: public behavior requires product approval.
  $m=New-Project 'M' "- Change type: refactor";Expect-Failure {& (Join-Path $root 'scripts/Test-ImplementationPreflight.ps1') -ProjectRoot $m} 'M refactor missing plan/invariants/ownership/tests';Init-Phase3 $m;& (Join-Path $root 'scripts/Test-ImplementationPreflight.ps1') -ProjectRoot $m
  $n=New-Project 'N' "- Change type: refactor";Init-Phase3 $n;'Affected files; ownership; regression test; rollback; public behavior: add new dashboard'|Set-Content (Join-Path $n '.studio/REFACTOR_PLAN.md');Expect-Failure {& (Join-Path $root 'scripts/Test-ImplementationPreflight.ps1') -ProjectRoot $n} 'N hidden feature in refactor'
  # O measured claims require method/evidence; P static release selects release only.
  $o=New-Project 'O' "- Performance required: yes";Init-Phase3 $o;'Lighthouse measured'|Set-Content (Join-Path $o '.studio/PERFORMANCE_REPORT.md');Expect-Failure {& (Join-Path $root 'scripts/Test-ImplementationPreflight.ps1') -ProjectRoot $o} 'O invented performance measurement'
  $p=New-Project 'P' "- Product type: static landing`n- Deployment required: yes";Init-Phase3 $p;& (Join-Path $root 'scripts/Test-ImplementationPreflight.ps1') -ProjectRoot $p;$plan=& (Join-Path $root 'scripts/Resolve-SpecialistPlan.ps1') -ProjectRoot $p;if($plan.Selected -notcontains 'release-engineer' -or $plan.Selected -contains 'operations-engineer'){throw 'P routing did not select release and skip operations.'}
  # Q production SaaS requires operations/release records; R never treats a build as deployment evidence.
  $q=New-Project 'Q' "- Backend required: yes`n- Persistence required: yes`n- Production SaaS handoff";Expect-Failure {& (Join-Path $root 'scripts/Test-ImplementationPreflight.ps1') -ProjectRoot $q} 'Q missing production SaaS records';Init-Phase3 $q;foreach($name in @('BACKEND_SPEC','API_CONTRACT','DATABASE_DECISION','DATA_MODEL','MIGRATION_PLAN','DATA_RETENTION','THREAT_MODEL','SECURITY_MODEL')){'# valid'|Set-Content (Join-Path $q ".studio/$name.md")};& (Join-Path $root 'scripts/Test-ImplementationPreflight.ps1') -ProjectRoot $q
  $r=New-Project 'R' "- Release required: yes";Init-Phase3 $r;'production complete; build succeeded'|Set-Content (Join-Path $r '.studio/RELEASE_PLAN.md');Expect-Failure {& (Join-Path $root 'scripts/Test-ImplementationPreflight.ps1') -ProjectRoot $r} 'R deployment claim without evidence'
  # S/T deterministic duplicates; U invalid static interaction; V project-link integrity; W forbidden root; X matching balance.
  $asset=Join-Path $work 'reference.txt';'fixture reference'|Set-Content $asset;$s=Add-ReferenceLibraryItem -AgentHome $libraryHome -FilePath $asset -Title 'Industry visual' -Industries dental -ProjectTypes saas -StyleFamilies editorial -PrimaryRole industry -SecondaryRoles visual -StrongSections hero;if($s.Outcome -ne 'new reference'){throw 'S initial ingest failed'};$dup=Add-ReferenceLibraryItem -AgentHome $libraryHome -FilePath $asset;if($dup.Outcome -ne 'exact duplicate'){throw 'S exact duplicate was copied'}
  $t=Add-ReferenceLibraryItem -AgentHome $libraryHome -Url 'HTTPS://Example.com/path/#x' -Title 'Product' -Industries dental -ProjectTypes saas -StyleFamilies editorial -PrimaryRole product -StrongSections pricing;$td=Add-ReferenceLibraryItem -AgentHome $libraryHome -Url 'https://example.com/path';if($td.Outcome -ne 'normalized URL duplicate'){throw 'T URL normalization failed'}
  $uFolder=Join-Path $s.Library ('references/'+$s.Id);'Verified hover effect.'|Set-Content (Join-Path $uFolder 'ANALYSIS.md');Expect-Failure {Test-ReferenceLibraryIntegrity -AgentHome $libraryHome} 'U unsupported interaction claim';'Unknown hover behavior; limitation: static capture.'|Set-Content (Join-Path $uFolder 'ANALYSIS.md');Test-ReferenceLibraryIntegrity -AgentHome $libraryHome|Out-Null
  Ensure-ReferenceProjectRecords -ProjectRoot $q|Out-Null;'ref-unknown0000'|Add-Content (Join-Path $q '.studio/references/PROJECT_REFERENCE_INDEX.md');Expect-Failure {Test-ReferenceProjectLinks -AgentHome $libraryHome -ProjectRoot $q} 'V missing global reference ID';Set-Content (Join-Path $q '.studio/references/PROJECT_REFERENCE_INDEX.md') "- `$($s.Id)";Test-ReferenceProjectLinks -AgentHome $libraryHome -ProjectRoot $q
  Expect-Failure {Initialize-ReferenceLibrary -AgentHome (Join-Path $work 'plugins/cache/bad')} 'W library root in plugin cache'
  $match=Find-ReferenceLibraryMatch -AgentHome $libraryHome -Industries dental -ProjectTypes saas -StyleFamilies editorial -Roles industry,visual,product -Sections hero,pricing;if($match.Matches.Count -lt 2 -or $match.BalancedSelection.Count -lt 2 -or -not $match.MissingRoleGaps){throw 'X matching does not return ranked reasons and role gaps.'}
  Write-Host 'Phase 3 fixtures passed: M-X. Classification: structural, state-machine, deterministic library behavior, targeted runtime fixture.'
} finally {if(Test-Path $work){Remove-Item -LiteralPath $work -Recurse -Force}}
