[CmdletBinding()]
param([Parameter(Mandatory)][string]$ProjectRoot)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'records/Test-RequiredProjectRecords.ps1')
$project=(Resolve-Path -LiteralPath $ProjectRoot).Path;$studio=Join-Path $project '.studio';if(-not(Test-Path -LiteralPath $studio)){throw "Missing project-local state directory: $studio"}
$validation=Test-RequiredProjectRecords -ProjectRoot $project;$req=$validation.requirements;$checks=@($validation.checks|Where-Object{$_ -and $_.PSObject.Properties['valid']});$invalid=@($checks|Where-Object{-not $_.valid});$missing=@($invalid|Where-Object{$_.status -eq 'missing'}|ForEach-Object{$_.record.path});$notApplicable=@($invalid|Where-Object{$_.record.metadata -and $_.record.metadata.status -eq 'not-applicable'}|ForEach-Object{$_.record.path});$contradictions=[Collections.Generic.List[string]]::new()
if($req.state.valid -and $req.state.record.metadata.data.currentState -notin @('approved','implementation-planning','implementation','specialist-verification','remediation')){$contradictions.Add('Project state does not allow implementation planning.')}
$scope=$checks|Where-Object{$_.record.metadata -and $_.record.metadata.recordType -eq 'active-scope'}|Select-Object -First 1;$plan=$checks|Where-Object{$_.record.metadata -and $_.record.metadata.recordType -eq 'implementation-plan'}|Select-Object -First 1;$criteria=$checks|Where-Object{$_.record.metadata -and $_.record.metadata.recordType -eq 'acceptance-criteria'}|Select-Object -First 1
if($scope -and $plan -and $scope.valid -and $plan.valid){$scopeIds=@($scope.record.metadata.data.active|ForEach-Object id);foreach($task in @($plan.record.metadata.data.tasks)){if(@($task.scopeIds|Where-Object{$scopeIds -contains $_}).Count -eq 0){$contradictions.Add("Task $($task.id) has no active-scope mapping.")}}}
if($plan -and $criteria -and $plan.valid -and $criteria.valid){$criteriaIds=@($criteria.record.metadata.data.criteria|ForEach-Object id);foreach($task in @($plan.record.metadata.data.tasks)){if(@($task.acceptanceCriteria|Where-Object{$criteriaIds -contains $_}).Count -eq 0){$contradictions.Add("Task $($task.id) maps to no declared acceptance criterion.")}}}
$planPath=Join-Path $studio 'reports/specialist-plan.json';$status=if($validation.valid -and $contradictions.Count -eq 0){'passed'}else{'blocked'}
if($status -eq 'passed'){& (Join-Path $PSScriptRoot 'Resolve-SpecialistPlan.ps1') -ProjectRoot $project -OutputPath $planPath|Out-Null}
$result=[ordered]@{schemaVersion=1;status=$status;projectState=$req.state.record.metadata.data.currentState;productType=$req.productType;surfaces=@($req.surfaces);requiredRecords=@($req.required|ForEach-Object name);validRecords=@($checks|Where-Object valid|ForEach-Object{$_.record.path});missingRecords=$missing;invalidRecords=@($invalid|ForEach-Object{$_.errors});notApplicableRecords=$notApplicable;contradictions=@($contradictions);specialistPlanPath=if($status -eq 'passed'){'.studio/reports/specialist-plan.json'}else{''};generatedAt=[DateTime]::UtcNow.ToString('o')}
$result|ConvertTo-Json -Depth 12|Set-Content -LiteralPath (Join-Path $studio 'IMPLEMENTATION_PREFLIGHT.json') -Encoding utf8
@('# Implementation preflight',"",("- Status: ``$status``"),("- Product type: ``$($result.productType)``"),("- Surfaces: ``$($result.surfaces -join ', ')``"),("- Missing records: "+$(if($missing.Count){$missing -join ', '}else{'none'})),("- Invalid records: "+$(if($invalid.Count){$invalid.record.path -join ', '}else{'none'})),("- Contradictions: "+$(if($contradictions.Count){$contradictions -join ' | '}else{'none'})),('- Machine-readable result: `.studio/IMPLEMENTATION_PREFLIGHT.json`.'))|Set-Content -LiteralPath (Join-Path $studio 'IMPLEMENTATION_PREFLIGHT.md') -Encoding utf8
if($status -ne 'passed'){throw "Implementation preflight blocked. See .studio/IMPLEMENTATION_PREFLIGHT.json"};Write-Host "Implementation preflight passed. Specialist plan: $planPath"
